### ISSUE TITLE
Visibilité des données confidentielles du profil

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#100]
@roidelapluie suggérait que les données telles que "Date de naissance" ne soient pas visibles "du grand public" dans les profils. 

Ma suggestion est la suivante : 
- Public : prénom, genre, pays, site web, adresse
- Lexpagien : + date de naissance, + ville, + création du compte
- Admin : + le reste :) 

En terme de modifications, c'est très simple à mettre en place, cela ne concerne que la template (vu, notamment, que les anniversaires ne sont pas visibles si on est pas loggué, du moins, il me semble).

Par contre, il conviendra d'adapter les `help_text` du modèle `Profile` pour refléter ces nouveaux changements. Peut-être que lorsqu'on consulte son propre profil, un indicateur précise quelles sont les informations qui sont visibles par quelles personnes.

**Comment by roidelapluie** [comment]
Maintenant il faut annoncer cela avec une ntification à tous qui pointe vers un message du forum à propos de ces changements.

`python app/manage.py notify --users=all --app=board --key=80 --action=-board/message/80 --title "Votre profil est maintenant plus confidentiel!"`

**Comment by AlexandreDecan** [comment]
Un moment, j'ai cru que t'avais implémenté ça sans que je ne le vois :-D

**Comment by roidelapluie** [comment]
:sunglasses:
