### ISSUE TITLE
Activer le support des websockets en prod

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#102]
- [x] Migrer de gunicorn à uwsgi
- [x] Installer Redis
- [x] Configurer redis pour systemd
- [ ] Configurer uwsgi pour systemd
- [x] Configurer nginx pour supporter les WS
- [ ] Configurer _settings_prod_ en conséquence

**Comment by AlexandreDecan** [comment]
@roidelapluie gevent ne semble pas avoir été porté vers Python 3, j'ai des `SyntaxError` tout con lors de son import. Or, il est nécessaire pour `ws_redis`...

**Comment by roidelapluie** [comment]
Pourquoi est ce que travis passe alors?

**Comment by AlexandreDecan** [comment]
Mon hypothèse est que uwsgi requiert une version plus ancienne, non compatible Python 3, de gevent.
Je continue de looker, mais bon, j'ai bien un 

> Traceback (most recent call last):
>   File "./wsgi_ws.py", line 5, in <module>
>     from ws4redis.uwsgi_runserver import uWSGIWebsocketServer
>   File "/var/www/Lexpage/venv/src/django-websocket-redis-master/ws4redis/uwsgi_runserver.py", line 3, in <module>
>     import gevent.select
>   File "/var/www/Lexpage/venv/lib/python3.4/site-packages/gevent/**init**.py", line 41, in <module>
>     from gevent.hub import get_hub, iwait, wait
>   File "/var/www/Lexpage/venv/lib/python3.4/site-packages/gevent/hub.py", line 289
>     except Exception, ex:
>                     ^
> SyntaxError: invalid syntax

qui m'empêche pour l'instant de poursuivre...

**Comment by roidelapluie** [comment]
https://github.com/gevent/gevent/issues/515

**Comment by roidelapluie** [comment]
pip install gevent==1.1rc3

**Comment by AlexandreDecan** [comment]
Ok, cela semble fonctionner. Par contre, le {{ WEBSOCKET_URI }} utilisé dans le template fait référence à 127.0.0.1:8001 (qui est le port sur lequel j'écoute en interne pour l'application principale, pas pour le websocket). A ton avis, je peux simplement remplacer ça par {{ WEBSOCKET_URL }} (qui contient /ws/) et omettre le domaine, ou c'est impératif de le garder ?

Je look à ça début d'aprem. ETA: fonctionel pour 16h ^^

**Comment by roidelapluie** [comment]
Oui ça devrait le faire

**Comment by AlexandreDecan** [comment]
Zut, il faut l'url longue. 
L'erreur vient d'ici : 
https://github.com/jrief/django-websocket-redis/blob/master/ws4redis/context_processors.py#L13

Il utilise request.get_host(), ce qui ne fonctionne pas avec un socket http basique.
Je vais voir si je peux contourner ça via des entêtes dans nginx.

**Comment by roidelapluie** [comment]
Pourquoi en fait?

**Comment by AlexandreDecan** [comment]
Parce que le request.get_host() retourne 127.0.0.1:8001, qui est l'adresse d'écoute du uwsgi principal, pas du uwsgi secondaire (qui s'occupe de traiter les requêtes WS). 

J'ai simplement forwardé l'entête http_host dans nginx, et ça fonctionne.
Le WS est bien joignable, par contre, j'ai des erreurs (et je les reçois par e-mail, pour faire suite à ta question sur Lexpage):

> Traceback:  
> File "/var/www/Lexpage/venv/src/django-websocket-redis-master/ws4redis/wsgi_server.py" in **call**
> 1.             websocket = self.upgrade_websocket(environ, start_response)
>    File "/var/www/Lexpage/venv/src/django-websocket-redis-master/ws4redis/uwsgi_runserver.py" in upgrade_websocket
> 2.         uwsgi.websocket_handshake(environ['HTTP_SEC_WEBSOCKET_KEY'], environ.get('HTTP_ORIGIN', ''))
>    Exception Type: OSError
>    Exception Value: unable to complete websocket handshake
>    Request data not supplied

**Comment by roidelapluie** [comment]
Tout le temps ou juste une fois?

**Comment by AlexandreDecan** [comment]
Tout le temps. Dans les logs uwsgi, j'ai 

> you need to build uWSGI with SSL support to use the websocket handshake api function !!!

**Comment by roidelapluie** [comment]
yum install openssl-devel.x86_64 && pip install uwsgi

**Comment by AlexandreDecan** [comment]
uwsgi n'est pas installé globalement (il tournerait en python 2), et dans l'environnement virtuel, il ne semble pas tenir compte de la présence d'openssl. Je vais forcer son build et retester.

**Comment by AlexandreDecan** [comment]
voilà, c'est bon
et ça semble marcher ! (j'ai fait un test avec girl271).

**Comment by AlexandreDecan** [comment]
Je passe les scripts sous systemd, puis je déploie.
