### ISSUE TITLE
La taille des messages du minichat peut être bypassée avec les substitutions

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#106]
Si je poste un message de 150 caractères, puis que je fais une substitutions de quelques caractères par un nombre plus grand, il est possible de bypasser la limite fixée de 150 caractères.

De plus, les substitutions sont GLOBALES, je crois que l'on ne devrait que substituer la première occurence trouvée.

**Comment by AlexandreDecan** [comment]
La limite de caractères lors du post initial n'est pas une contrainte forte en soi. L'idée est simplement d'avoir un "petit message". Si on peut l'agrandir avec la substitution, ce n'est pas bien grave (de mon point de vue, en tout cas :-D). Dans tous les cas, il ne sera pas possible de dépasser la limite du modèle :-D

Mais ok pour ne substituer que la première occurrence.

**Comment by AlexandreDecan** [comment]
La substitution ne s'effectue que pour la première occurrence trouvée.
