### ISSUE TITLE
Notifier l'utilisateur avec contrib.message instantanné lors de modification de message

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#107]
Lorsque l'on utilise s/foo/bar dans le minichat, je propose que l'utilisateur reçoive un feedback direct via contrib.message, comme pour les anchors.

**Comment by AlexandreDecan** [comment]
:+1:

**Comment by AlexandreDecan** [comment]
La notification s'affiche en cas de modification, et informe sur les **nouvelles** notifications.

**Comment by roidelapluie** [comment]
ok. c'est overkill d'informer sur les notifications supprimées?

**Comment by AlexandreDecan** [comment]
Non, mais le use case n'est pas le même. Je pense qu'on va plus facilement modifier un message pour corriger une faute (dans l'ancre ou ailleurs, d'où l'idée d'afficher les **nouvelles** notifications) que pour retirer quelqu'un qui était à priori concerné par le message.

Le but de la notification est surtout de prévenir l'utilisateur de qui est notifié, non pas pour qu'il sache qui va avoir la notification, mais plutôt pour identifier si éventuellement, il n'a pas fait une faute de frappe en écrivant l'ancre.
