### ISSUE TITLE
Tuner *collectstatic* pour minifier à la volée

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#110]
Split de #67

Tuner python manage.py collectstatic de sorte à minifier les fichiers statiques (css et JS) à la volée, si un minifieur est disponible.

**Comment by roidelapluie** [comment]
C'est une feature de django compressor.

**Comment by AlexandreDecan** [comment]
Je préfère définir et utiliser notre propre "handler de static" (https://docs.djangoproject.com/en/1.9/howto/custom-file-storage/) et https://pypi.python.org/pypi/csscompressor/ ainsi que https://github.com/rspivak/slimit pour rester en pur Python. Je préfère éviter une dépendance supplémentaire, surtout si on peut faire le traitement simplement de notre coté.

**Comment by AlexandreDecan** [comment]
C'est implémenté (non sans douleur vu la qualité de la documentation au sujet des Storage !). 

Par contre, le gain est vraiment, vraiment, vraiment négligeable: les librairies externes sont déjà minifiées, et on a pratiquement rien en interne qui justifie une minification.

Je n'ai pas pu tester localement si les fichiers minifiés faisaient encore fonctionner Lexpage correctement : django sert les versions non-minifiées quand DEBUG=True, et si je le passe en False, il refuse de servir les fichiers statiques (pourtant, je suis pratiquement sûr qu'il le fait lors des tests Selenium).

**Comment by roidelapluie** [comment]
Tu aurais du faire une PR. Travis aurait testé.

**Comment by AlexandreDecan** [comment]
Ouais, j'aurai du :-D Au moins une branche.

**Comment by AlexandreDecan** [comment]
J'ai revert, y a un fichier (au moins ! script.js) qui ne passe plus en prod. 
Les tests Travis se basent donc bien sur les fichiers dans les répertoires static locaux, pas static_pub.

**Comment by AlexandreDecan** [comment]
Les commits sont visibles dans la branche minify-static (le HEAD correspond à l'état avant le revert du master).

**Comment by roidelapluie** [comment]
@AlexandreDecan réouvre
