### ISSUE TITLE
Définir des tâches Grunt pour Sass et Nunjucks

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#111]
Split de #67

Définir des tâches Grunt (ainsi que les dépendances à installer via npm) pour compiler le(s) style(s) Sass et compiler les différentes templates Nunjucks.

**Comment by AlexandreDecan** [comment]
Je ferme, ou tu souhaites ajouter le support pour Sass aussi ?

**Comment by roidelapluie** [comment]
Je compte ajouter sass. Surtout que la st Valentin approche ;-)

**Comment by AlexandreDecan** [comment]
Je sais qu'on travaille en binome, mais tu n'es pas obligé de me faire un cadeau :-D

**Comment by roidelapluie** [comment]
Lol pas envie d'avoir 271 claques ;-)

**Comment by roidelapluie** [comment]
De plus j'aimerais ajouter un test Travis pour nunjucks/sass pour vérifier que la minification est correcte. Le but n'est pas de minifier à la volée parce que ce serait une trop grande barrière à l'entrée.

**Comment by AlexandreDecan** [comment]
Elle ne donne pas de claques, elle arrache les yeux :-D

**Comment by AlexandreDecan** [comment]
On peut fermer ?

**Comment by AlexandreDecan** [comment]
@roidelapluie up ?

**Comment by roidelapluie** [comment]
Pas tanr que la PR est ouverte
