### ISSUE TITLE
Déplacer la gestion des notifications du minichat vers l'application notifications

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#115]
Comme indiqué sur #101, je me demande si ce ne serait pas mieux que les signaux gérant les notifications des autres applications soient en fait définis dans l'application de notification, de sorte à que le couplage se fasse depuis _notifications_, et non pas dans l'autre sens.

**Comment by AlexandreDecan** [comment]
@roidelapluie ton avis là-dessus ? :)

**Comment by roidelapluie** [comment]
:+1:

**Comment by roidelapluie** [comment]
Du coup on abandonne les signaux?

**Comment by AlexandreDecan** [comment]
Non : on intercepte les signaux des autres apps dans l'application notifications (une sorte d'Observer mais sur les modèles).

**Comment by roidelapluie** [comment]
ok

**Comment by AlexandreDecan** [comment]
Considérer #112 (et le PR #125 !) avant.

**Comment by AlexandreDecan** [comment]
Finalement, ça ne me semble pas une bonne idée. Ok, le couplage sera fait dans une direction qui semble plus naturelle mais pour d'autres applications (comme blog), il y a tellement de logique à vérifier avant de générer une notification que ça n'a pas de sens d'aller faire cela dans l'app notifications.

**Comment by AlexandreDecan** [comment]
@roidelapluie tu penses quoi de https://github.com/django-notifications/django-notifications ? 
J'ai un système finalement pas si éloigné. Est-ce que tu crois qu'on gagnerait à passer sur une app externe ?

**Comment by roidelapluie** [comment]
Inutile sauf si tu veux conserver les notifications lues
