### ISSUE TITLE
L'horodatage des notifications du minichat n'est pas correct après modification

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#116]
Lorsqu'un message est adressé à _@machin_ sur le minichat, l'utilisateur _machin_ reçoit une notification. Un e-mail est automatiquement envoyé à _machin_ au bout d'un certain temps si cette notification n'a pas encore été lue.

Actuellement, lorsque l'on poste à un message pour _@machin_ et qu'on le modifie par la suite (via "s/replaced/replace"), la notification initiale est supprimée et re-créée (au cas où les anchors changent entre le message initial et le message modifié). Le souci, c'est que la nouvelle notification est horodatée de l'heure de sa création, ce qui repousse le moment auquel l'email est envoyé. 
Or, si la modification n'a pas concerné une ancre, il n'y a pas de raison à ce que la notification soit regénérée. 

https://github.com/AlexandreDecan/Lexpage/blob/master/app/minichat/signals.py

Une amélioration serait de ne plus intercepter _pre_save_ pour _remove_notifications_, et de changer le comportement du _post_save_ dans _send_notifications_. Cette amélioration consisterait à:
1. Récupérer la liste des notifications encore existantes associées à ce message (on sait que ça concerne `app=minichat` et `key=message.pk`. Stockons dans `old_targets` la liste des utilisateurs associés à ces notifications.
2. Calculer la nouvelle liste des destinataires via `message.parse_anchors()`, notons `new_targets`.
3. Pour chaque `old_targets` qui n'est pas dans `new_targets`, on supprime la notification. Pour chaque `new_targets` qui n'est pas dans `old_targets`, on génère une nouvelle notification.

Le gros inconvénient de cette méthode est que l'on risque de regénérer une notification pour un utilisateur ayant déjà dismiss la première notification.

En alternative, mais qui fait plus appel à du "bricolage", on peut:
1. Intercepter _pre_save_ et récupérer le message dans la database avant qu'il ne soit sauvé. 
2. On compare `old_message.parse_anchors()` avec `new_message.parse_anchors`.
3. On supprime les notifications pour les utilisateurs qui sont dans _old_ mais pas dans _new_, et on génère des notifications pour ceux qui sont dans _new_ et pas dans _old_.

Cette deuxième approche me semble mieux. 
@roidelapluie qu'en penses-tu ?

**Comment by roidelapluie** [comment]
je crois que on devrait mettre à jour la notification ainsi que l'heure du dernier message, et n'autoriser sa modification que si aucun autre user n'a posté après le message.

**Comment by AlexandreDecan** [comment]
Je préfère limiter la modification dans le temps (par exemple, dans les 30 minutes qui suivent) plutôt que de limiter en fonction de la présence d'une réponse. Mais même en limitant dans le temps, cela signifie qu'on va potentiellement générer une nouvelle notification auprès de chaque utilisateur qui a déjà dismissé la notification précédente. 

Je reste partisan de l'approche _pre_save_ et de récupérer l'instance modifiée dans la db.

**Comment by roidelapluie** [comment]
Dans ce cas l'approche 2 semble mieux. le but de limiter au vu des autres réponses c'est surtout pour éviter de fausser une discussion.

**Comment by roidelapluie** [comment]
(et dans le cas ou il y a eu un message on publie le s/foo/bar comme ça, sans modifier l'autre message)

**Comment by AlexandreDecan** [comment]
Je comprends l'idée d'éviter une fausse discussion (surtout qu'on a aucune trace de l'historique des messages). Je préfère limiter dans le temps alors (5, 10, 15, 30 minutes ?). Si on tente de modifier un message trop vieux, alors on devrait recevoir une notification de type **error** plutôt que de poster le message contenant le code de la substitution. On doit pouvoir faire ça assez facilement: si `substituted` n'est pas `None`, on calcule le delta entre `now` et la date du message. Si le delta est inférieur à x minutes, on ne change rien à ce qui est codé pour l'instant, sinon on retourne un code d'erreur.

**Comment by roidelapluie** [comment]
ok

**Comment by roidelapluie** [comment]
Deux choses dans ce ticket:
- [ ] Éviter un refresh inutile des notifications
- [ ] Empecher de modifier un vieux message

**Comment by roidelapluie** [comment]
Il y a quelque chose d'impossible:

on ne peut pas éviter de reenvoyer la notification si elle a été dismiss.
- on doit utiliser pre_save pour accéder au message de la DB
- on ne peut pas envoyer de nouvelle notification en pre_save parce que la notification n'a pas d'ID

**Comment by AlexandreDecan** [comment]
Si, c'est possible ;-)
Désolé, j'avais fait le commit hier, mais je ne l'ai pas pushé car j'étais sur autre chose niveau tests :(
