### ISSUE TITLE
Empêcher la modification d'un message du minichat après x minutes

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#118]
Comme indiqué dans #116 : 

> Je comprends l'idée d'éviter une fausse discussion (surtout qu'on a aucune trace de l'historique des messages). Je préfère limiter dans le temps alors (5, 10, 15, 30 minutes ?). Si on tente de modifier un message trop vieux, alors on devrait recevoir une notification de type error plutôt que de poster le message contenant le code de la substitution. On doit pouvoir faire ça assez facilement: si substituted n'est pas None, on calcule le delta entre now et la date du message. Si le delta est inférieur à x minutes, on ne change rien à ce qui est codé pour l'instant, sinon on retourne un code d'erreur. 

@roidelapluie on part sur quelle durée avant d'empêcher la modification ? Vu la nature "instantanée" du minichat, je propose que ça ne dépasse pas les 30 minutes, voir peut-être même 5 ?

**Comment by roidelapluie** [comment]
Ok pour 5 minutes
