### ISSUE TITLE
Trouver une manière d'avoir un keepalive

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#128]
Grace aux websockets, fini les rechargements intempestifs du minichat, et donc de la date de dernière mise à jour.

Il faut remédier à cela.

Une solution c'est de parler dans le chat puis de recharger la page :-D mais on peut trouver mieux.

**Comment by AlexandreDecan** [comment]
Est-ce qu'on ne peut pas conserver le système actuel (via le middleware) et mettre à jour en parallèle la date de dernière visite à chaque heartbeat ?

**Comment by roidelapluie** [comment]
On ne gère pas les heartbeat, tout est dans la lib. De plus, c'est agressif (heartbeat rapprochés)

**Comment by AlexandreDecan** [comment]
Ca aurait du sens d'ajouter un support dans l'app minichat pour le "en ligne", et de faire en sorte que le navigateur puisse envoyer à intervalle régulier (3 minutes ?) un ping pour signaler qu'il est présent sur la page.

**Comment by AlexandreDecan** [comment]
Je suis d'avis d'avoir une application "online" dédiée à faire cela : 
- Contient le middleware qui met à jour l'heure de visite.
- Fournit un context_processor permettant de générer la liste des connectés dans les templates. 
- Fournit une vue pour "ping/pong" comme tu le proposes ici.
- Fournit un static dont l'unique objectif est de faire un "ping" à intervalles réguliers (je propose de se baser sur la valeur du timeout défini dans les settings).

Par la suite, on pourra réfléchir à ajouter un mécanisme permettant de mettre à jour la liste des utilisateurs en ligne, mais essayant de limiter les possibilités d'automatiser un tracer de visites avec ça (on en rediscutera).

Qu'en penses-tu ? En alternative à ce qui se trouve ci-dessus, on peut éventuellement simplement intégrer chacun de ces points dans l'application "minichat" actuelle, ce qui reste cohérent (et minimise le travail à faire par dessus ton PR).

**Comment by roidelapluie** [comment]
Oui, ça a du sens d'abuser du minichat pour ça
- [ ] déplacer le middlerware de mise à jour de l'heure de visite dans l'appli minichat
- Quelle est le but du Context processor? Ce sera overkill étant donné que cela ne serait disponible que pour les lexpagiens connectés.
- Ne mettre à jour la date de visite "que" dans le ping pong, pour éviter le middleware?

**Comment by AlexandreDecan** [comment]
Effectivement, pas de context processor (on utilise actuellement un template tag ce qui est largement suffisant). Le déplacer est suffisant. 

Concernant la date de visite, je pense qu'on doit la mettre à jour coté serveur directement, afin que le ping ne soit utilisé qu'au mieux au bout de quelques minutes. Je n'ai pas en tête d'autres façons simples de procéder que via le middleware :s

**Comment by roidelapluie** [comment]
Oui mais pourquoi veux tu cela? Si le ping fait le job, plus besoin de middleware. Un middleware c'est très très lourd comme solution en comparaison

**Comment by AlexandreDecan** [comment]
Le ping induit une requête supplémentaire, qui nécessite de mettre toute la machinerie Django en place. Le middleware est essentiellement juste un callable qui est appelé à chaque requête, je ne trouve pas cela bien lourd.
