### ISSUE TITLE
Retirer SELENIUM_AVAILABLE

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#130]
On devrait arrêter de regarder si selenium est présent

 https://github.com/AlexandreDecan/Lexpage/blob/master/app/tests_helpers.py#L27

**Comment by AlexandreDecan** [comment]
Pourquoi ?

**Comment by roidelapluie** [comment]
C'est pas joli ; on checke déjà si il y a un driver de défini

**Comment by AlexandreDecan** [comment]
Ok. Je te laisserai regarder ça ;-) 

Je m'occupe de quelques merge en ce début d'aprem.

**Comment by roidelapluie** [comment]
mmh est ce que la prod a besoin des tests? selenium est dans settings_dev.txt

**Comment by AlexandreDecan** [comment]
Non, je ne lance jamais les tests en prod (sauf cas vraiment particulier mais dans ce cas-là, j'installe aussi settings_dev de toute façon).

**Comment by AlexandreDecan** [comment]
L'issue ne sera plus pertinente après le prochain "gros" refactoring pour les WS. 
Je reviendrai là-dessus quand je réintroduirai Selenium.
