### ISSUE TITLE
Définir et utiliser un décorateur pour les signaux ne s'appliquant pas aux fixtures.

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#133]
Voir https://github.com/AlexandreDecan/Lexpage/pull/125/files#r50616967

**Comment by AlexandreDecan** [comment]
Quelque chose du genre: 

``` python
from functools import wrap

def ignore_fixture(f):
  @wraps(f)
  def wrapper(*args, **kwargs):
    if not kwargs.get('raw', False):  
      return f(*args, **kwargs)
    else:
      return None
  return wrapper
```

@roidelapluie ?

On le mettrait où ? On pourrait faire un _helpers_signals_ ou _helpers_decorators_ dans _/app/_...

**Comment by roidelapluie** [comment]
commons/decorators ?

**Comment by AlexandreDecan** [comment]
J'ai l'impression qu'il vaut mieux consider _commons_ comme étant une application fournissant des services communs à d'autres applications du projet. Et quand je dis "service", je parle de features, pas vraiment de "morceaux de code". 

Si on place ce décorateur dans _commons_, ne faudrait-il pas déplacer les helpers aussi dans _commons_ dans ce cas ? Est-ce que ce décorateur est vraiment spécifique à _commons_ (pas pour moi), ou est-ce qu'on souhaite juste le mettre dans _commons_ parce que c'est là qu'on fourre tout ce qui n'a pas une place dans une app spécifique ? :-) Auquel cas, je me demande s'il ne serait pas judicieux de le mettre simplement dans /app/.

**Comment by roidelapluie** [comment]
le probleme de /app c'est qu'on inclus sans contexte, et import decorator ça pourrait facilement collusionner avec une autre lib... d'où mon idée d'un commons.decorators

**Comment by AlexandreDecan** [comment]
En effet, cela me semble un bon argument. Mais est-ce qu'on ne peut pas appeler le module "helpers" ou "helpers_signal" pour éviter ce type de conflit ? 

J'avoue être mitigé sur le fait d'aller placer ces helpers dans une sous-app (à la rigueur, un module dédié à stocker du code partagé entre les apps, mais pas une app en tant que telle).

**Comment by roidelapluie** [comment]
Ok :-)

**Comment by AlexandreDecan** [comment]
OK pour un sous-module dédié à stocker le code partagé, ou ok pour le placer dans le root module avec un nom qui évite les shallow ? ;-)

**Comment by roidelapluie** [comment]
lexpage.decorators

**Comment by AlexandreDecan** [comment]
Ok, donc un sous-module. Je propose qu'on le nomme "helpers" (pour ne pas avoir un nom lié au brand ^^) et qu'on y put les différents helpers (donc redis.py, websockets.py, decorators.py, ...)

Je m'en occuperai dans la semaine, ça ne devrait pas être bien long (à part que les différents helpers sont utilisés un peu partout dans les tests :-D)
