### ISSUE TITLE
Retirer la dépendance à compass

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#141]
On devrait pouvoir compiler les themes de la lexpage sans compass.

**Comment by AlexandreDecan** [comment]
Est-ce vraiment nécessaire ? Quelle est la rationale derrière l'issue ?

**Comment by roidelapluie** [comment]
ça apporte quoi d'avoir cette dépendance ruby? IIRC ce n'est pas nécéssaire à bootstrap

**Comment by AlexandreDecan** [comment]
Je ne sais pas, j'ai suivi un bête tuto pour mettre en place ça quand Tchou s'y était attaqué.

**Comment by roidelapluie** [comment]
Je regarderai à ça

**Comment by roidelapluie** [comment]
il y a d'autres prios, ça roule maintenant.
