### ISSUE TITLE
autocomplétion des auteurs dans la recherche

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#142]
La recherche comporte un field author, qui pourrait utiliser l'autocompletion.

**Comment by AlexandreDecan** [comment]
Non, parce que l'autocompletion concerne tous les utilisateurs enregistrés. Ca aurait du sens de ne proposer que les utilisateurs pour lesquels des résultats matchent.

**Comment by AlexandreDecan** [comment]
Reopen, car c'est mieux que rien et ce n'est pas un gros boulot en fait.

**Comment by roidelapluie** [comment]
Ce serait fou de faire ce que tu proposes, ça implique faire une pré-recherche dans chacun des éléments (slogans, blog, minichat, ...)

**Comment by AlexandreDecan** [comment]
Ou d'avoir un filtre sur la liste des users pour ne sortir que ceux qui sont auteurs d'un élément de la catégorie recherchée.
