### ISSUE TITLE
Déplacement de messages

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#15]
Ajouter la possibilité de déplacer un message vers un autre topic. Probablement via une action dans l'admin (pas besoin que ça soit exposé sur le site). En particulier, tenir compte automatiquement de ce qui ne l'est pas actuellement : 
- Les marqueurs de lecteur à mettre à jour (calculer le dernier message précédent le message déplacé, et mettre à jour les entrées)
- Actualiser le nombre de messages postés dans chaque discussion concernée (+1 -1, ouais, pas dur). 
- Mettre à jour le lien vers le "dernier message" de la conversation si nécessaire (dans un sens comme dans l'autre). 
- Ajout d'une notification à l'auteur du message pour signaler le déplacement de son message.

**Comment by roidelapluie** [comment]
@AlexandreDecan le plus simple serait d'implémenter une suppression du message original et une recréation dans l'autre post?

**Comment by AlexandreDecan** [comment]
Probablement, à condition de conserver l'historique du message.
