### ISSUE TITLE
Délimiter messages lus et non lus sur le minichat

### ISSUE THREAD

**Issue by adyxax** [AlexandreDecan/Lexpage#154]
Est-il envisageable d'avoir une barre de séparation entre les messages déjà lus et les nouveaux? En comparant le timestamp de dernière activité/connection au timestamp des messages du minichat peut-être?

Cette utilisation du timestamp bien que sous optimale (ça ne garantie pas qu'un utilisateur avait bien lu le minichat) serait "mieux que rien" et souvent pertinente. Personnellement je lis le minichat à chaque visite et check le dernier message avant de C-W la page.

**Comment by roidelapluie** [comment]
![m2](https://cloud.githubusercontent.com/assets/291750/12651702/fde19546-c5e7-11e5-8448-9a90eb5b7c32.png)

**Comment by AlexandreDecan** [comment]
C'est discret, j'aime bien ! 

Je propose qu'on injecte le `last_visit` du user dans `__base.html` (un peu comme on faisait avec `{{ username }}`). Le `last_visit` étant mis à jour après le chargement de la page, cela veut dire qu'il est toujours "un cran en retard", et donc on peut l'utiliser comme moment de référence pour colorer ou non les messages. Je propose que via la template nunjucks, on ajoute une classe "new" au message dont la date dépasse le seuil du`last_visit`.

T'en penses quoi @roidelapluie ?

**Comment by roidelapluie** [comment]
Plutôt que last_vist, minichat_unread_flag? Comme ça on met a jour quand on poste un message

**Comment by roidelapluie** [comment]
quoique.

**Comment by roidelapluie** [comment]
je tente quelque chose ce soir

**Comment by AlexandreDecan** [comment]
Je ne suis pas partisan d'une solution "lourde" à base de flags, je préfère reposer sur la date de dernière visite. Si vraiment tu veux partir sur des flags, alors je suggère qu'un mouseover d'au moins 1 seconde réinitialise le flag, afin d'avoir un moyen de marquer le minichat comme lu, sans que ça ne soit trop "envahissant". 

C'est sensible aux mauvaises manipulations, mais "pas trop", je trouve.

**Comment by roidelapluie** [comment]
Je parlais juste du nom de la variable, de telle manière a la modifier quand on poste un message

**Comment by roidelapluie** [comment]
mais on peut aussi gérer dans le template qu'à partir de notre dernier message posté tout est lu meme si plus récent que la date de visite

**Comment by AlexandreDecan** [comment]
Ok pour le nom de la variable, j'avais mal compris ;-) 

Ce qu'on peut faire, c'est fixer cette variable à la date du `last_visit` et automatiquement la fixer à la date du message posté quand on poste un message. Il est important par contre de reposer sur l'heure du serveur, et non l'heure du client (et donc d'éviter de fixer cette date à "now()" dans le client, car le now() du client n'est pas forcément le now() du serveur, d'où l'idée de fixer la date sur l'heure du message, quand on en poste un).

**Comment by roidelapluie** [comment]
On n'a pas besoin de cela, on détecte déjà quand on a un message a nous.

Je viens de blinder les tests de #152 . Je peux partir de la?

Je fais quoi quand une personne poste deux fois mais qu'on a lu qu'un des deux? Je splitte en un message rouge et un bleu? Ou bien je change le bord de la partie non lue?

**Comment by AlexandreDecan** [comment]
Oui, tu peux partir de #152. Je propose d'ailleurs que tu regroupes les deux au sein d'un même PR ?

> Je fais quoi quand une personne poste deux fois mais qu'on a lu qu'un des deux? Je splitte en un message rouge et un bleu? Ou bien je change le bord de la partie non lue?

Changer le bord de la partie non-lue me semble bien. 

> On n'a pas besoin de cela, on détecte déjà quand on a un message a nous.

Je ne suis pas sûr de comprendre :-)

**Comment by roidelapluie** [comment]
Voilà

**Comment by roidelapluie** [comment]
![m3](https://cloud.githubusercontent.com/assets/291750/12658868/ed70e314-c60b-11e5-89a8-b3e9dfec4bd5.png)

**Comment by roidelapluie** [comment]
![m5](https://cloud.githubusercontent.com/assets/291750/12658925/2a653bc6-c60c-11e5-9134-122d1aeb9099.png)

**Comment by AlexandreDecan** [comment]
:+1: je review, je merge, je push ;)

**Comment by roidelapluie** [comment]
voila
