### ISSUE TITLE
Auto dissmiss des notifications minichat

### ISSUE THREAD

**Issue by adyxax** [AlexandreDecan/Lexpage#156]
Ce serait super cool d'avoir un auto dissmiss des notifications en @nick sur le minichat.

Par exemple, répondre sur le chat pourrait suffir à indiquer que l'on a lu les messages précédents qui nous étaient destinés.

Merci d'avance de considérer cette idée!

**Comment by AlexandreDecan** [comment]
Je peux comprendre l'intérêt de dismisser la notification dans certaines circonstances (par exemple, comme @roidelapluie le suggérait pour les discussions privées, lorsqu'on lit la discussion alors qu'on a un nouveau message). Par contre, pour le minichat, je ne trouve pas que l'action de "répondre" soit une garantie suffisante qu'on ait lu le message ciblé par la notification, et donc je ne pense pas qu'il soit judicieux de faire un dismiss automatique sous "présomption" qu'on a lu le message parce qu'on répond/poste sur le minichat. 

A discuter !

**Comment by AlexandreDecan** [comment]
Un avis supplémentaire ? ;-)

**Comment by roidelapluie** [comment]
Moi j'aimerais bien avoir les notifications visibles sur le minichat et pouvoir dismisser en cliquant sur le message. Ça évite de devoir ouvrir les notifications pour rien.

**Comment by AlexandreDecan** [comment]
Sans doute faudrait-il alors réfléchir sur la pertinence d'avoir une notification quand on est targeté par une ancre dans le minichat, non ?

**Comment by roidelapluie** [comment]
C'est utile. Par contée c'est lourd d'aller lire ça dans les archives. Il faudrait donner aux archives un look plus "minichat"

**Comment by roidelapluie** [comment]
En fait virer les archives pour les remplacer par un minichat paginé par mois :-)

**Comment by AlexandreDecan** [comment]
D'accord pour les archives #166
