### ISSUE TITLE
Chargement des anciens messages du minichat ?

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#159]
Avec la mise en évidence des messages non-lus depuis la dernière visite, il devient intéressant de parcourir davantage que les 20 messages affichés sans avoir a aller dans les archives (car les archives ne peuvent pas mettre en évidence les messages non-lus, puisqu'elle ne dispose pas de l'information pour le faire). 

Peut-on considérer le fait d'avoir un lien "< précédent - suivant >" (le "précédent" en bas du scroll, le suivant en haut du scroll ?) de sorte à pouvoir remonter dans le temps sans avoir à quitter la page ? Il faut voir si c'est techniquement pas trop embêtant à intégrer (sans doute supprimer le refresh automatique du div si on est parti "dans le temps" ?)

**Comment by roidelapluie** [comment]
On peut implémeter notre propre système de pagination, qui comporterait 2 parametres:
- Date_Min -> last_date par défaut, comme ça on a tous les messages non lus
- Number_of_messages -> 20 par défault avec un bouton "+" en bas du minichat pour en charger plus.

le tout avec une hard limit à 100.

**Comment by AlexandreDecan** [comment]
La seconde option me tente bien (dans ce cas, je suppose qu'on supprime la pagination coté client, et qu'on ne fait que compléter la structure de données à afficher). Je n'aime pas trop la 1ere option cumulée à la hard limit: le comportement pour le visiteur dépend d'une limite dont il n'a pas forcément connaissance (et je comprends la nécessité d'avoir une telle limite, cela dit ;-)

Si on part sur l'option 2, il faut réfléchir concrètement à ce que l'on va faire. Je suis d'avis d'implémenter des vues pour : 
- Obtenir les 20 premiers messages suivant un numéro de message donné. Par défaut, si aucun numéro n'est fourni, alors ce sont les 20 plus récents qui sont renvoyés.
- Obtenir les 20 derniers messages précédant un numéro de message donné.

De la sorte : 
- Si le refresh du minichat est le premier effectué sur la page, il n'a pas de numéro de message de référence, et peut donc appeler la 1ere vue pour obtenir les 20 derniers.
- A chaque refresh, la 1ere vue est appelée avec le numéro du dernier message connu du client.
- Un bouton "+" en bas du minichat permet de charger davantage de message, dans ce cas, la seconde vue est appelée avec le message le plus ancien actuellement affiché. 

Coté client, on doit "juste" maintenir une liste des messages reçus, et vu ce que retournent les vues, on a normalement pas de collisions possibles dans les messages reçus (mais à cause des race conditions, il faudra quand même s'assurer qu'on n'injecte pas deux fois le même message). 

Ca te semble ok ?

**Comment by AlexandreDecan** [comment]
http://www.django-rest-framework.org/api-guide/pagination/#cursorpagination ?
Demande sans doute un peu plus de chipotage au niveau client, mais ferait l'affaire pour le reste.

**Comment by roidelapluie** [comment]
ben justement on a besoin des deux pour etre sur que on a un minimum de messages

**Comment by AlexandreDecan** [comment]
Je ne suis pas sûr de comprendre ce que tu veux dire (cf. https://github.com/AlexandreDecan/Lexpage/issues/159#issuecomment-177136175)

**Comment by roidelapluie** [comment]
Les autres solution hélas sont moins solides. Quand on a chargé tous les messages (ou les 100 premiers), on est envoyé vers les archives

**Comment by AlexandreDecan** [comment]
Je vais regarder si je peux trouver quelque chose. En l'état, je n'aime pas trop parce que le serveur pourrait avoir à sortir 100 messages à la fois au lieu de 20, et que la limite parait un peu artificielle. 

Par contre, si on confie la pagination coté client (par exemple, en ayant un paramètre supplémentaire pour la vue `before` qui prend une date), cela signifie qu'il faut, coté client, avoir un filtre permettant de retirer les messages en double (soit ça, soit introduire un paramètre supplémentaire `after`, à utiliser dans le "refresh"). Dans ce cas là, on peut se passer du filtre pour les doublons, et ça ne "cassera" que s'il y a deux messages qui sont postés exactement à la même seconde et qui sont sur des "pages" séparées.
