### ISSUE TITLE
Conversion automatique des URL dans le bbcode

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#168]
Cela fait bien longtemps que Tchou le demandait, et les premiers essais n'avaient rien donné, mais il serait intéressant d'avoir une conversion automatique des urls dans le forum (sans que ça n'interfère avec les balises actuelles pouvant contenir également des urls).

L'approche classique de convertir les liens en ancres HTML n'est pas fonctionnelle (à cause des autres balises). Par contre, peut-être pourrait-on convertir les urls dont les bords ne sont pas =, ] ou [ pour éviter ce souci.

**Comment by roidelapluie** [comment]
C'est quoi le probleme ? si un mot commence par http:// ou https:// on peut le convertir non?

**Comment by AlexandreDecan** [comment]
Pas s'il se trouve dans une autre balise, genre [url=http://truc]machin[/url]. 
Il faut "juste" appliquer la regex des liens (sans balise) avant les autres. Mais je voudrai en profiter pour refactoriser un peu cette partie du code qui est un vrai b.. :)

**Comment by roidelapluie** [comment]
D'ou le commence par... \b en regex

**Comment by AlexandreDecan** [comment]
"=" et "]" sont des word boundaries (donc \b les match), non ?
Je ferai des tests cet aprem si j'ai un peu de temps.

**Comment by roidelapluie** [comment]
aah `(\s|^)` alors

**Comment by AlexandreDecan** [comment]
yep, quelque chose comme ça. Il reste encore le souci ds url entre parenthèses "(http://blabla)" qui est encore un usage assez courant du copy&paste d'url. C'est pour ça que je pense qu'on pourrait voir pour matcher toute url qui est précédée d'autre chose que "]" et "=" (qui correspond à [url=x], [url]x, [img]x, [embed]x, etc.).

**Comment by AlexandreDecan** [comment]
Voilà qui est fait. Je ne suis pas extrêmement satisfait (1) parce que je n'ai pas refactorisé grand chose dans le code de ce fichier, (2) parce qu'il faudrait utiliser une grammaire plutôt que des expressions régulières pour ce genre de choses.
