### ISSUE TITLE
Date complète dans l'affichage des archives des billets

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#169]
Cf. http://www.lexpage.net/board/message/7569/

Il faudrait en profiter pour retirer les templates correspondant à l'ancienne disposition des billets, afin de s'y retrouver un peu plus facilement. 

Je suggère qu'on parte soit sur une approche en listing proche de l'actuelle apparence des archives (avec juste le correctif demandé par Anca), soit une approche plus proche de la page d'accueil (sans l'embed, mais sous forme de pseudo-vignette).

Préférence pour le (1) quand même.

**Comment by roidelapluie** [comment]
tu as skippé la partie refactoring de ce ticket non?

**Comment by AlexandreDecan** [comment]
Oui et non : je n'ai rien touché aux anciennes templates (ou presque), mais elles sont encore utilisées pour tout ce qui concerne le listing (archives, étiquettes, etc.). 

Par contre, il faut que je peaufine le seuil pour masquer/afficher une étiquette, ainsi que la valeur utilisée pour la taille.
