### ISSUE TITLE
Selenium tests do not work with Travis and Selenium 3.4.3

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#180]
https://travis-ci.org/AlexandreDecan/Lexpage/jobs/251432936

**Comment by AlexandreDecan** [comment]
Selenium 3.4.3 still does not work with Firefox/Travis. See:
See https://travis-ci.org/AlexandreDecan/Lexpage/jobs/251941315

More information, and a possible upcoming fix: 
https://github.com/SeleniumHQ/selenium/issues/3884

**Comment by AlexandreDecan** [comment]
The initial bug was fixed in c7a9eb1 but we now have several tests that fail. They all seems to be related to a Marionnette specific bug, that prevents element to be clicked if they are not visible... 

I tried several things (adding a delay before clicking on the object, forcing its display, etc.) with no success.

**Comment by AlexandreDecan** [comment]
@roidelapluie est-ce que tu as une idée ? as-tu déjà rencontré quelque chose de similaire pour lequel il y a une solution "magique" ? :-) J'ai installé exactement la même conf localement, ce qui me permet d'avancer plus vite que d'attendre que Travis crache un failed, mais je n'ai aucune idée comment solutionner le souci pour l'instant, à part attendre un éventuel fix upstream (s'il arrive un jour, est-ce réellement un bug ou une feature ? ^^).

**Comment by roidelapluie** [comment]
On 08 Sep 08:40, Alexandre Decan wrote:
> @roidelapluie est-ce que tu as une idée ? as-tu déjà rencontré quelque chose de similaire pour lequel il y a une solution "magique" ? :-) J'ai installé exactement la même conf localement, ce qui me permet d'avancer plus vite que d'attendre que Travis crache un failed, mais je n'ai aucune idée comment solutionner le souci pour l'instant, à part attendre un éventuel fix upstream (s'il arrive un jour, est-ce réellement un bug ou une feature ? ^^). 
> 

Non; firefox est à la peine avec selenium.

> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/AlexandreDecan/Lexpage/issues/180#issuecomment-328138949

-- 
 (o-    Julien Pivotto
 //\    Open-Source Consultant
 V_/_   Inuits - https://www.inuits.eu

**Comment by AlexandreDecan** [comment]
Quel est ton avis pour gérer Travis par rapport à ça ? Je "skipIf" dans le code les tests concernés si le webdriver est gecko, ou bien j'"allow failure" le cas Firefox ?

**Comment by roidelapluie** [comment]
Allowfailure

**Comment by AlexandreDecan** [comment]
Ca m'embêtait de laisser ces fichus tests (surtout qu'en local, je rencontre le même souci). Je contourne le problème en simulant un hover sur le dropdown des notifications plutôt que de simuler un click (qui visiblement provoque aussi un hover, et donc le dropdown s'ouvre et se ferme directement). 

Je pense que Travis va apprécier maintenant, mais on perd le fait de vérifier qu'un click sur un "close" d'une notification ne ferme pas le dropdown. Je vais voir si je peux explicitement ajouter un test en ce sens.
