### ISSUE TITLE
Migration de Debian vers CentOS

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#22]
Le serveur tourne actuellement sous Debian, une vieille Wheezy avec quelques backports et beaucoup de problèmes à cause d'une tentative de faire tourner Docker sous les noyaux OVH. 

Maintenant que Lexpage (et les autres projets tournant dessus, sauf exception de ceux qui tournent sous Node) fonctionne dans un environnement virtuel, il serait peut-être temps de s'occuper de la partie serveur, et de réinstaller quelque chose de frais. 

A tenir en compte :
- [x] La configuration de Nginx et des différents projets tournant derrière. 
- [x] La configuration de php/php-fpm qui fait tourner Piwik (ou abandon de Piwik ? On s'en moque un peu des statistiques et je ne m'en sers que pour Lexpage). 
- [x] Les projets Node (à priori sont déjà convertis en Python et/ou abandonnés, donc no care)
- [x] Le serveur MariaDB (à migrer vers du Postgresql ?)
- [x] Le workflow de backup à base de Dropbox et de logrotate (à updater)
- [x] La configuration d'iptables
- [x] Les crons
- [x] Clés SSH
- [x] Les avatars du Lexpage et la configuration en prod

**Comment by roidelapluie** [comment]
J'imagine que tu vas passer en CentOS 7

Dans ce cas, ne t'embete pas avec des outils comme supervisord; utilise systemd directement. Un service init pour systemd c'est super simple à écrire et il y a des instructions pour le relancer auto en cas de crash etc.

Exemple avec gunicorn: https://github.com/Matt-Deacalion/systemd-django/blob/master/services/django-website.service

à mettre dans /etc/systemd/system/lexpage.service

**Comment by roidelapluie** [comment]
Pour python3.4 https://www.softwarecollections.org/en/scls/rhscl/rh-python34/

**Comment by roidelapluie** [comment]
python3.4 est aussi disponible dans epel (yum install epel-release)

**Comment by AlexandreDecan** [comment]
Oui, CentOS 7. Je compte passer par epel (notamment pour y piocher DNF, j'ai pris l'habitude :-D). Y a un intérêt à utiliser rhscl ? Python 3.4 n'est pas dans les dépôts "officiels" sous CentOS?

Merci pour l'info sur supervisord, j'avais déjà pris connaissance de systemd et je me demandais justement dans quelle mesure le premier était encore utile. Ton message me confirme qu'il vaut mieux ne pas s'encombrer avec les 2 ;-)

**Comment by roidelapluie** [comment]
Non ce n'est pas officiel. EPEL ça devrait être bon. Les RHCL vont plus isoler le python que EPEL (epel metttra python dans /usr/bin, rhcl dans /opt/python34/bin).

**Comment by AlexandreDecan** [comment]
Ok, merci ;)
