### ISSUE TITLE
Support HTTPS avec https://letsencrypt.org/

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#36]
Après la migration vers CentOS (ou autre), proposer un support pour https via un certificat https://letsencrypt.org/. 

Je suppose que l'idée est d'imposer https une fois que ça sera en place.

**Comment by roidelapluie** [comment]
Attention, pas uniquement server side. certaines parties du code devont être changées également.

https://github.com/AlexandreDecan/Lexpage/blob/8e7ff89a70589c8f3d4a51fc150c7ad54f21495f/app/profile/views.py#L61

**Comment by roidelapluie** [comment]
Aussi, https://ma.ttias.be/firefox-nightly-starts-marking-login-forms-in-http-as-insecure/

**Comment by roidelapluie** [comment]
Il faudra faire attention car les avatars servis en HTTP feront un warning "mixed content"

**Comment by AlexandreDecan** [comment]
Seulement ceux qui sont hébergés sur lexpage, ou cela concerne aussi les extérieurs ?
Parce que si ce sont les internes, pas de souci... 

Au niveau des libs JS/CSS/fonts externes, il faut aussi adapter je suppose ?

**Comment by AlexandreDecan** [comment]
Je reconsidèrerai cela plus tard, quand j'envisagerai de passer l'ensemble des webapps du serveur en HTTPS.

**Comment by roidelapluie** [comment]
Il faudrait y repenser.

Firefox va bientôt marquer lexpage comme insecure.

https://developer.mozilla.org/en-US/docs/Web/Security/Insecure_passwords

**Comment by roidelapluie** [comment]
De plus pour HTTP/2 il faut du HTTPS. Les browsers n'ont pas implémenté le protocole HTTP/2 sans TLS

**Comment by AlexandreDecan** [comment]
Je pense qu'on a encore largement de la marge avant que ça ne devienne urgent d'y penser ;-) 
Je vais me renseigner pour voir ce que ça implique au niveau du serveur, nginx et django.

**Comment by roidelapluie** [comment]
Pourquoi utopia? c'est vraiment vraiment trivial.

**Comment by AlexandreDecan** [comment]
Parce que ce n'est pas urgent :-) 

Je vais d'abord me renseigner sur les implications au niveau du serveur avant d'aller plus loin :-)

**Comment by AlexandreDecan** [comment]
Si j'ai nginx en frontal configuré pour relayer via HTTPS, est-ce que j'ai besoin de faire en sorte que Django soit conscient du HTTPS ?

**Comment by roidelapluie** [comment]
non

**Comment by AlexandreDecan** [comment]
Ok, donc les seuls changements pour Lexpage, c'est de convertir les "http" en dur par des "https" (ou plutôt de définir un settings à cet égard).

**Comment by roidelapluie** [comment]
il ne devrait plus y avoir de http en dur.

Je te propose de ne pas force le HTTPS dans un premier temps, comme ça on ne casse pas les avatars etc.

**Comment by AlexandreDecan** [comment]
Oui, je vais utiliser un settings pour le préfixe des URL (notamment pour le mail d'inscription, etc.). 
Ou alors je peux configurer nginx pour systématiquement rediriger http / 80 vers https / 443 ?

**Comment by AlexandreDecan** [comment]
Mmmh en relisant ton message, je ne suis en fait pas sûr de parler de la même chose ;-)

**Comment by AlexandreDecan** [comment]
Tu voulais peut-être plutôt parler de "//" comme début d'url des avatars, comme ça c'est dépendant du schema utilisé sur la page courante ?

**Comment by roidelapluie** [comment]
Non parce que les avatars proviennent de sites externes pour la plupart. Donc il faudra décider ce que l'on fait.

**Comment by roidelapluie** [comment]
Le fait est que les browsers refuseront de charger les avatars servis en http.

**Comment by AlexandreDecan** [comment]
Je voulais dire pour les avatars hébergés sur Lexpage. 
Mais ok pour les avatars externes, j'avais oublié ça.

**Comment by roidelapluie** [comment]
Pour ceux hebergés sur lexpage tu peux même omettre le domain: /images/foo.png

**Comment by AlexandreDecan** [comment]
Il faut que je regarde si Django permet de faire ça dans un URLfield. Je pense que c'était la raison pour laquelle j'avais injecté le domaine courant. 

https://docs.djangoproject.com/en/1.9/ref/validators/#urlvalidator
Visiblement, non... :(

**Comment by AlexandreDecan** [comment]
Il y a aussi le souci de l'embed qui fait appel à une ressource externe. Visiblement, il supporte HTTPS, donc ça ne devrait pas être trop embêtant.

Et y a Piwik (mais ça ne devrait pas être un souci non plus vu).

**Comment by roidelapluie** [comment]
Piwik, à mon humble avis devrait être forcé en HTTPS même sur le site en HTTP :-)

**Comment by AlexandreDecan** [comment]
Oui ;)

**Comment by AlexandreDecan** [comment]
Pour lecture ultérieure : https://www.nginx.com/blog/free-certificates-lets-encrypt-and-nginx/

**Comment by AlexandreDecan** [comment]
Bon, je pense qu'il est temps de faire quelque chose suite à ce ticket ;-) 

Je vais débuter (demain, si j'ai du temps) la configuration du serveur afin de pouvoir choper un certificat via Let's Encrypt, et déployer ça sur le serveur. Dans un premier temps, je vais laisser http et https cohabiter le temps de faire les tests, et puis petit à petit, on supprimera le support d'http en forçant l'usage d'https.

**Comment by AlexandreDecan** [comment]
Fini !
