### ISSUE TITLE
websockets

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#42]
Implémenter les websockets pour le minichat et les notifications

**Comment by AlexandreDecan** [comment]
Tu as un support correct des websockets dans Django ? 
A ma connaissance, c'est encore bloquant à cause de wsgi, non?

**Comment by roidelapluie** [comment]
On trouvera une solution propre :)

**Comment by roidelapluie** [comment]
Voir #43

**Comment by AlexandreDecan** [comment]
Tu connais crossbar / autobahn ? J'en avais entendu parler sur sametmax.com il y a quelques mois, cela pourrait être une solution, vu que ça a l'air d'être supporté/intégrable avec Django ?
http://crossbar.io/docs/Adding-Real-Time-to-Django-Applications/

Je n'ai pas encore lu la page, ni regardé dans quel état ("production-ready"?) c'était...

**Comment by roidelapluie** [comment]
On 23 Dec 03:07, Alexandre Decan wrote:

> Tu connais crossbar / autobahn ? J'en avais entendu parler sur sametmax.com il y a quelques mois, cela pourrait être une solution, vu que ça a l'air d'être supporté/intégrable avec Django ?
> http://crossbar.io/docs/Adding-Real-Time-to-Django-Applications/
> 
> Je n'ai pas encore lu la page, ni regardé dans quel état ("production-ready"?) c'était... 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/AlexandreDecan/Lexpage/issues/42#issuecomment-166864078

C'est quoi l'avantage? Ici c'est fonctionnel et je vais pouvoir retirer
les sales hack et on pourra lancer les tests 'normalement' sans serveur
en plus. Bref ça devient propre.

## 

 (o-    Julien Pivotto
 //\    Open-Source Consultant
 V_/_   Inuits - https://www.inuits.eu

**Comment by AlexandreDecan** [comment]
Aucune idée, je sais juste qu'ils avaient l'air bien motivés par ce projet :-D

Je m'occupe de réorganiser les settings/requirements sur le master.

**Comment by AlexandreDecan** [comment]
Pour résumer sur le déploiement, il faut que je prenne en compte : 
- Un redis sur le serveur (pas de configuration particulière, juste observable en local ?)
- Un uwsgi en parallèle du gunicorn pour traiter les WS. 

Au niveau de systemd: 
- Ajouter redis, pas de démarrage automatique
- Ajouter une dépendance vers redis pour Lexpage, redis starté avant Lexpage
- Ajouter uwsgi pour le WS, pas de démarrage automatique
- Ajouter une dépendance vers uwsgi pour Lexpage, starté avant Lexpage

Au niveau de nginx:
- Ajouter une règle pour grepper les requêtes WS et les transférer au socket uwsgi

C'est bien ça ?

**Comment by roidelapluie** [comment]
Oui cela devrait être bon.

**Comment by AlexandreDecan** [comment]
Rien à prévoir coté backend de session et librairie pgsql ?

**Comment by roidelapluie** [comment]
à priori ça devrait être ok, tu parlais de psychopg mais je n'ai pas creusé de ce côté.

**Comment by roidelapluie** [comment]
Nous limitons la feature aux users connectés, ce qui fait genre 2-3 users maximum ?

**Comment by AlexandreDecan** [comment]
En pic, je dirai plutôt 5 ou 6. Mais j'imagine que le souci des sessions ne se pose que si un même utilisateur fait plein de connexions simultanées, ce qui devrait être limité.

**Comment by roidelapluie** [comment]
Je crois que l'on devrait attendre:
- Django 1.9.1

**Comment by AlexandreDecan** [comment]
Pas de souci

**Comment by roidelapluie** [comment]
Et voilà, Django 1.9.1 est released

**Comment by AlexandreDecan** [comment]
Je propose qu'on ouvre un nouveau ticket une fois que #60 est intégré.
