### ISSUE TITLE
Les erreurs 500 ne sont plus interceptées

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#44]
Test : http://www.lexpage.net/posts/archives/1000/2/
Il suffit de revenir une fois en arrière (janvier 1000) et cela provoque une erreur (que je ne compte pas corriger) parce qu'il n'y a pas de reverse pour décembre 999. Par contre, au lieu d'afficher une jolie page avec notre pote Bob, ça affiche un "Internal Server Error" de nginx.

**Comment by AlexandreDecan** [comment]
L'erreur est bien interceptée, mais il semble qu'une autre erreur se produise pendant le traitement. 
Je pense que cela vient d'éléments qu'on a ajouté récemment dans `__base.html`.

**Comment by AlexandreDecan** [comment]
Visiblement, cela viendrait de `{% with preferred_theme=user.profile.get_theme|default:DEFAULT_THEME %}`
Je m'y attaque.

**Comment by AlexandreDecan** [comment]
Fonctionne en local, pas en ligne oO

**Comment by roidelapluie** [comment]
Quelle est l'erreur ? Ça marche sur l'ancienne prod?

**Comment by AlexandreDecan** [comment]
Oui, cela fonctionnait avant. 
Le comportement attendu est que l'erreur 500 est "redirigée" vers la template 500.html. Cette page affiche alors un joli petit message. Actuellement, cela provoque une hideuse internal server error, parce qu'une nouvelle erreur se produit pendant le traitement de l'erreur 500 précédente. Cette nouvelle erreur est en fait dûe à l'usage de DEFAULT_THEME (devenu THEMES.DEFAULT depuis) dans la template __base.html qui est étendue par 500.html. 

Lors du traitement d'une 500, Django ne fournit aucun `context` à la vue. Visiblement, l'absence de ce contexte pose problème (alors que ce n'était pas le cas avant, où par exemple j'accédais à des valeurs du contexte sans que ça ne "plante" à cause de leur absence). 

J'ai créé une vue spécifique pour gérer les 500, afin de pouvoir lui refiler un `context`, puisqu'il faut juste finalement passer par le context_processors qui s'occupe de définir THEMES.DEFAULT, et ça marche en local. Mais pas en ligne !

**Comment by roidelapluie** [comment]
On peut mettre le style dans un bloc {% block %} et l'overwrite dans 500.html

**Comment by AlexandreDecan** [comment]
J'avais testé, sans succès. J'ai l'impression qu'il compile les blocks tout de même, même quand ils sont overridés. Je vais déjà essayer de comprendre pourquoi ça marche en local (avec DEBUG = False). Je pense que ça doit venir du serveur de dev...

**Comment by AlexandreDecan** [comment]
Gunicorn en local me fait la même chose que le serveur de dev. Je vais voir du coté de Nginx s'il n'y a pas une sorte d'override quelconque :(

[Edit: visiblement, non, vu que Django ne retourne pas une 500 quand l'erreur est interceptée. Je ne vois pas d'où ça peut venir !]

**Comment by roidelapluie** [comment]
Est ce que tu veux ma clé ssh? On ne peut pas créer de message sur le forum, même erreur 500

**Comment by AlexandreDecan** [comment]
Je vais régler le cas du forum, c'est autre chose: une clé étrangère non respectée (parce qu'elle n'est pas nullable, et que je mets le default à -1, fichu MySQL qui autorise ça :-D)

Pour les erreurs 500, je vais chercher sur le servuer si je trouve quelque chose. Je prendrais ta clé ssh dès que j'abandonne :-)

**Comment by roidelapluie** [comment]
Tu es sur que ce n'est pas Django qui retourne une 500, et nginx qui droppe vers cette page?

**Comment by roidelapluie** [comment]
genre debug=false crée une vrai erreur 500?

**Comment by roidelapluie** [comment]
a mon avis uwsgi revoie les 500 correctement...

**Comment by AlexandreDecan** [comment]
Bah en debug=False, localement, gunicorn renvoie bien un 200 avec la page "Bob a tout pété". 
Je vais voir du coté de nginx en effet, s'il n'y a pas une option à définir pour qu'en cas d'erreur 500, il affiche tout de même le contenu de la réponse.

**Comment by AlexandreDecan** [comment]
Problème du forum réglé (foreignkey, que tristement je fous à db_constraint=False ^^).

**Comment by AlexandreDecan** [comment]
Je confirme : 
- Avec DEBUG = True, la page 500 qui affiche la trace complète de l'erreur est renvoyée avec le code 500 par Gunicorn.
- Avec DEBUG = False, la page 500 qui affiche le "Bob" est renvoyée avec le code 200 par Gunicorn. Je ne comprends donc pas pourquoi en ligne, cela ne fonctionne pas...

**Comment by AlexandreDecan** [comment]
J'ai une piste : le logguer semble avoir un souci.

**Comment by roidelapluie** [comment]
et TEMPLATE_DEBUG?

**Comment by AlexandreDecan** [comment]
Même valeur que DEBUG (par défaut, et fixé dans les settings aussi). Par contre, mon "warning.log" se crée bien, mais il ne se remplit pas... Je vais désactiver le logguer et tester. Ensuite, je testerai en mettant un simple "bonjour" à la place de 500.html ^^

**Comment by AlexandreDecan** [comment]
Désactiver le logguer ne change rien. Par contre, mettre un simple texte (sans appel à une template parent ou autre) dans le 500.html fonctionne. Je suis donc convaincu qu'il s'agit bien d'un souci lié à cette template... Reste à comprendre pourquoi en local, ça fonctionne, alors qu'en ligne ça plante !
