### ISSUE TITLE
Impossible de s'identifier

### ISSUE THREAD

**Issue by adyxax** [AlexandreDecan/Lexpage#47]
Salut Guybrush, c'est Sysson!

Depuis l'update d'aujourd'hui impossible de me loguer. J'ai fait plusieurs tentatives juste avant minuit, rien n'y fait! Avant de faire mot de passe oublié et de tenter comme ça je préférais signaler et gardant l'option pour toi de débuguer, je risque de ne pas être le seul affecté.

Au plaisir,

**Comment by roidelapluie** [comment]
Pas de souci de mon côté.

**Comment by AlexandreDecan** [comment]
Salut Sysson.

J'ai eu le souci sur un de mes appareils également, hier. Bon login et bon password, mais le site n'a pas l'air d'accord. Est-ce que tu peux vérifier en supprimant le cookie (ou en passant en navigation privée) si cela le fait aussi ? 

Le problème s'est résolu de lui-même chez moi, je ne sais pas pourquoi...

**Comment by roidelapluie** [comment]
Peut etre en utilisant explicitement new.lexpage.net ça peut marcher? comme workaround temporaire.

**Comment by AlexandreDecan** [comment]
Le problème s'est posé chez moi quand j'ai accédé à www.lexpage.net (nouvelle ip, après propagation des DNS) : j'étais déloggué, et je crois que le cookie (ou la clé de chiffrement ? pourtant elle n'a pas changé) devait être responsable de ces soucis.

**Comment by AlexandreDecan** [comment]
Tu étais sur quelle adresse, Sysson ?

**Comment by adyxax** [comment]
J'étais sur www.lexpage.net, utiliser new.lexpage.net n'a pas résolu le problème. J'avais testé en navigation privée mais sans succès, j'aurais du le préciser. Supprimer le cookie ne me sauve donc évidemment pas non plus et je suis certain de ne pas avoir changé mon mot de passe dans mon sommeil!

**Comment by AlexandreDecan** [comment]
Est-ce que tu as bien écrit ton pseudo ? Je veux dire : "Sysson" avec un "S" majuscule ? 
Anca semble avoir eu le même problème...

**Comment by adyxax** [comment]
Whoa, j'avais mis un S majuscule à l'inscription il y a 10 ans!!!

J'en déduis que le logins qui était avant case insensitive ne l'est plus ou un truc du genre. Mon login était enregistré en minuscule dans mon browser depuis aussi loin que je m'en rappelle.

En tout cas bien vu et merci ;-)

May the Lexpage be with you.

**Comment by AlexandreDecan** [comment]
Je pense que par défaut, l'ancien mysql faisait une comparaison non sensible à la casse, alors que le nouveau postgres est sensible à la casse. C'est embêtant, je trouve, et de ce que je vois dans les tickets Django, il n'y a pas grand chose de trivial à faire pour contourner ça. 

Je vais m'y attaquer dès que j'ai du temps, je rouvre le ticket.
