### ISSUE TITLE
Supprimer whitenoise

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#49]
Whitenoise est le module Django permettant de servir des fichiers statiques. En production, je repose complètement sur nginx pour tout ce qui se trouve dans /static. En local, le serveur intégré de Django sert les fichiers statiques si `DEBUG = True`. Le seul intérêt de whitenoise, c'est de servir les fichiers statiques en local si le site est lancé via gunicorn ou uwsgi. 

Je propose donc de retirer whitenoise pour libérer une dépendance. 
- [x] requirements.txt
- [x] uwsgi.py
- [x] settings.py
- [x] readme?
- [x] ... ?

**Comment by roidelapluie** [comment]
Attention, pourrait être requis pour Selenium.

**Comment by AlexandreDecan** [comment]
Pas si on utilise le serveur de développement intégré de Django, non ?

**Comment by AlexandreDecan** [comment]
958cd7a
