### ISSUE TITLE
Inscription à SauceLabs

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#51]
Bonjour

Peux tu t'enregistrer sur https://saucelabs.com/opensauce/ afin que l'on puisse ajouter les tests selenium dans travis-ci? https://docs.travis-ci.com/user/gui-and-headless-browsers/

Merci

**Comment by roidelapluie** [comment]
Le but principal est de pouvoir tester efficacement les websockets.

**Comment by AlexandreDecan** [comment]
Je vais regarder. Je sais que les unittests de Django ont un support pour Selenium, mais faut-il des dépendances supplémentaires ? Si oui, peux-tu proposer un requirements.txt spécifiques pour le dev ?

**Comment by roidelapluie** [comment]
je vais regarder. pour SauceLab, tu peux chiffrer ton access key: https://docs.travis-ci.com/user/encryption-keys/ pour la stocker publiquement dans le .travis.yml

**Comment by AlexandreDecan** [comment]
Oui, j'ai utilisé la même approche pour déployer automatiquement des paquets sur PyPi. 
Y a un push qui arrive dans quelques minutes avec une base pour `requirements_tests.txt`.

**Comment by AlexandreDecan** [comment]
.travis.yml mis à jour, j'espère que ça marchera ;-) 
J'ai 14 days de free trial sur sauce labs, je suppose que ça reste valide après pour les projets open source ?

**Comment by roidelapluie** [comment]
C'est ce qu'ils disent: free unlimited for open source. Tu t'es bien inscrit avec ton compte github?

**Comment by AlexandreDecan** [comment]
Non, j'ai créé un compte from scratch... 
Zut...

**Comment by AlexandreDecan** [comment]
1f09cb6 ok

**Comment by roidelapluie** [comment]
Saucelab a été retiré. La raison est qu'ils ne supportent pas les pull requests, ce qui le rend pas mal inutile.

J'étais assez LOL quand j'ai vu ça.

https://docs.travis-ci.com/user/sauce-connect/

https://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests

**Comment by AlexandreDecan** [comment]
Pas terrible :) J'ai vu que tu l'avais retiré, je l'ai donc retiré du travis.yml (mais pourquoi ils ont pas utilisé yaml au lieu de yml ? :-D)

**Comment by roidelapluie** [comment]
Pour nous rappeler le bon vieux temps de Frontpage et de ses .htm :)
