### ISSUE TITLE
Changement du titre de la page quand on reçoit/supprime des notifications

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#52]
Une fois le support des WS mergés, il serait bien d'avoir un compteur des notifications dans le titre (Lexpage (1)) par exemple, qui se mettrait à jour tout seul.

Il vaut mieux limiter la taille de la PR sur les websockets et ajouter les features de manière incrémentielle afin que cela soit facile de faire du code-review dessus, d'ou la création de ce ticket, qui pourra être traité quand on aura acquis de l'expérience sur les websockets en prod.

**Comment by AlexandreDecan** [comment]
Peut-on motiver davantage cette issue ? L'indicateur dans la barre de navigation me semble déjà assez présent, surtout vu la faible priorité des notifications (si on en rate une, et qu'on ne la voit que quelques heures après, quelle importance ? ^^).

**Comment by roidelapluie** [comment]
J'utilise une extension firefox qui fait ceci:

![foo](https://cloud.githubusercontent.com/assets/291750/12307034/3142c010-ba3d-11e5-9ce7-21685e6ed36b.png)

également si je "pin" le tab.

**Comment by roidelapluie** [comment]
Pour cela la page doit juste ajouter un (x) à la fin du titre. D'autres sites le font, dont Facebook.

**Comment by roidelapluie** [comment]
![fcb](https://cloud.githubusercontent.com/assets/291750/12307087/7101dd80-ba3d-11e5-93c1-113c57b9f721.png) Facebook met le compteur devant

**Comment by AlexandreDecan** [comment]
Ok, ça ne devrait pas être trop difficile à mettre en place, non ?
`document.title` ne suffirait pas ?

**Comment by roidelapluie** [comment]
@AlexandreDecan Quand même, j'ai rajouté des validateurs pour refuser les (x) x étant un nombre dans les titres.
