### ISSUE TITLE
Le hook des `profile` est en conflit avec les fixtures

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#54]
Le hook des `profile` se déclenche lors de la création d'un user :
https://github.com/AlexandreDecan/Lexpage/blob/master/app/profile/models.py#L20

Le souci est que lors du chargement de fixtures, lorsque les users sont chargés, ils sont déjà créés à cause des profils précédents. 

http://stackoverflow.com/questions/3499791/how-do-i-prevent-fixtures-from-conflicting-with-django-post-save-signal-code

Il y a un moyen simple d'empêcher ça.

**Comment by roidelapluie** [comment]
Ce sera réglè avec #48

**Comment by AlexandreDecan** [comment]
Parfait. T'es plus rapide que moi ;-)

**Comment by roidelapluie** [comment]
je vais quand meme devoir virer des fixtures internes de django

https://travis-ci.org/AlexandreDecan/Lexpage/builds/98653118

**Comment by AlexandreDecan** [comment]
Oui, mais ce n'est pas bien grave car elles seront re-créées automatiquement si tu fais un `migrate` pour initialiser la db.

**Comment by roidelapluie** [comment]
oui; d'ailleurs les tests sont verts à nouveau \o/

**Comment by roidelapluie** [comment]
C'était fix dans #42 aussi :-)

**Comment by AlexandreDecan** [comment]
Oui, mais #42 est pas encore mergé et j'ai besoin du hook pour cloner l'environnement de prod facilement ;-)

**Comment by roidelapluie** [comment]
ok, bon amusement avec la nouvelle interface d'admin ;-)

**Comment by AlexandreDecan** [comment]
Je ne vois pas de changement oO ?

[Edit : Ah oui, ok, j'avais pas synchro les fichiers statiques]

**Comment by AlexandreDecan** [comment]
Quel intérêt d'aller reskin l'admin s'ils ne la rendent pas mobile-compliant au passage ? 
On perd en lisibilité et en espace, dommage...

**Comment by roidelapluie** [comment]
Sinon y a https://github.com/django-admin-bootstrap/django-admin-bootstrap

**Comment by AlexandreDecan** [comment]
J'avais testé à une époque, et j'avais eu quelques soucis avec. Ca doit dater d'y a 2 ans environ. Tu as eu l'occasion de l'utiliser (professionnellement ?) depuis ? Je vais ajouter une issue pour garder l'idée en stock...

**Comment by roidelapluie** [comment]
Pas testé. http://levit.be semble l'utiliser pour eux et leurs clients.
