### ISSUE TITLE
Websockets pour 'django.contrib.messages'

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#55]
Il serait bien de faire passer 'django.contrib.messages' par des websockets pour avoir un affichage instantané des messages.

**Comment by AlexandreDecan** [comment]
Je ne pense pas que ça soit intéressant, les notifications sont là pour être prévenu "en temps réel". `django.contrib.messages` est utilisé typiquement suite à un formulaire ou quelque chose du genre, donc dans des cas où ça n'a aucun intérêt d'utiliser des websockets. 

Je pense que le seul cas où cela peut s'avérer intéressant, c'est quand on poste un message sur le minichat avec un `@target`. `django.contrib.messages` est utilisé dans ce cas pour indiquer la liste des destinataires reconnus (les `@target`). Ca pourrait être géré directement par le JS du minichat. 

Je ne suis pas convaincu par les websockets pour ajouter du dynamisme au site. Je pense qu'une bonne API rest couvre 95% des cas, les 5% restants pouvant être gérés effectivement par un canal de communication WS. Le websocket ne devrait servir qu'à envoyer des notifications pour que les composants (serveurs ou clients) puissent prendre les actions adéquates.

**Comment by roidelapluie** [comment]
OK. C'est en effet le minichat qui était visé. Peut être que l'on peut ajouter le message dans le minichat en lui même ou faire une "vraie" notification ?

**Comment by AlexandreDecan** [comment]
Une vraie notification sera trop intrusif : en général, on s'attend à ce que tout usage de `@target` soit valide. S'il faut commencer à cliquer sur la notification pour dismisser cette info, c'est un peu pénible. 

Je suis d'avis aussi que le minichat ne contienne pas de message "statut" pour signaler si quelque chose a bien eu lieu ou pas. En fait, l'idéal, ce serait que chaque `@target` soit transformé en lien cliquable, ainsi on peut facilement identifier lesquels sont valides ou pas, mais ça nécessite soit de stocker "en dur" lesquels sont valides (afin de ne pas les valider à chaque fois), soit de faire une requête pour vérifier la validité du `@target`, ce qui peut être couteux. 

Agir dans l'autre sens n'est pas une solution non plus : notifier quand un `@target` est détecté comme étant invalide. Essentiellement parce qu'il y a beaucoup de faux positifs possibles (adresse e-mail, usage du symbole @ dans un autre contexte, etc.). 

Je n'ai pas de solution en tête pour l'instant, et, par conséquent, rien de mieux à proposer :-) 
Mais dans l'absolu, je préfère éviter au maximum d'ajouter trop de nouvelles fonctionnalités utilisant les websockets. Je ne suis pas encore convaincu de l'importance des features qui y sont liées par rapport à la dette technique que cela peut représenter.
