### ISSUE TITLE
Minichat UX et websockets

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#56]
Il serait bien de mettre à jour FA vers la dernière version

**Comment by AlexandreDecan** [comment]
Euh ok, mais... pourquoi ? :-) 
On n'utilise aucune des nouvelles icones ;-)

**Comment by roidelapluie** [comment]
Il y a des icones utilisées dans le status du minichat, à voir lesquelles on utilisera au final. Je poste des screenshots:

Pour les users déconnectés (non authentifiés)
![off](https://cloud.githubusercontent.com/assets/291750/12035453/70f2dbd4-ae3d-11e5-88d0-3b9126fe17f3.png)

Les users connectés, première tentative de connection:

![conn](https://cloud.githubusercontent.com/assets/291750/12035462/82b5ddb2-ae3d-11e5-96df-42da17f5bf16.png)

Les users connectés, le websocket est connecté:

![on](https://cloud.githubusercontent.com/assets/291750/12035472/8dd0c9a0-ae3d-11e5-9285-11e97c96ca24.png)

Les users connectés mais le websocket est déconnecté:

![dis](https://cloud.githubusercontent.com/assets/291750/12035479/97f24b5c-ae3d-11e5-84ac-eca985775c1f.png)

**Comment by AlexandreDecan** [comment]
Je pense qu'il ne faut pas d'icones pour les utilisateurs déconnectés. Pour les autres, ne serait-il pas plus judicieux de les placer sur le bouton permettant d'envoyer un message ? 
L'icone "fa-spin" lors d'un chargement, et une icone "fa-warning" au cas où le WS est déconnecté ?

**Comment by roidelapluie** [comment]
Non parce que fa-warning est utilisée lors d'une erreur d'envoi, et fa-spin pendant l'envoi.

**Comment by roidelapluie** [comment]
De plus le minichat fonctionne sans les websockets donc il serait trompeur de mettre la notification visuelle au même endroit.

**Comment by roidelapluie** [comment]
Et le boutton est clickable est permet de forcer la  reconnection au WS

**Comment by roidelapluie** [comment]
La notification pour les non connectés étant celle que j'aimais le moins, je peux fermer ce ticket.

**Comment by AlexandreDecan** [comment]
Alors faut-il vraiment un indicateur du statut du WS, sachant que ça marche "quoiqu'il arrive" ? 
Je n'aime pas trop l'idée d'une icône qui soit juste "technique". Surtout, ce que je n'aime pas, c'est la position : cet emplacement est typiquement utilisé ailleurs pour des "options supplémentaires", pas pour afficher un statut. A la rigueur, un texte en muted en dessous de l'input field me semble plus judicieux, non ?

**Comment by roidelapluie** [comment]
C'est le statut et aussi le bouton pour forcer la reconneciton (en fait c'est surtout pratique en local).

Le texte en muted cela semble au contraire trop intrusif à mon sens ?

**Comment by AlexandreDecan** [comment]
Non, puisque c'est un statut "en cas d'erreur". En gros, si la connexion se fait, on n'affiche rien de particulier. En cas d'erreur, le bouton a un "warning", et en cas de perte de connexion, le bouton pourrait avoir un "warning" aussi + un texte en dessous en muted (text-alert ?) disant que la connexion a été perdue, et qu'on peut cliquer sur le bouton pour la recréer ?

**Comment by roidelapluie** [comment]
Ah ouais, ça semble cool :-) J'implémente

**Comment by roidelapluie** [comment]
Nouveau design:

![dis](https://cloud.githubusercontent.com/assets/291750/12041360/fd59f304-ae70-11e5-8058-0f13b5b48f4b.png)

**Comment by AlexandreDecan** [comment]
Possible de placer ce bloc en dessous ? Soit au dessus de l'input field (je pense que ce sera mieux), soit en dessous. Comme ça, la partie "messages" reste cohérente.

**Comment by roidelapluie** [comment]
![dis](https://cloud.githubusercontent.com/assets/291750/12051019/94c233d2-aefd-11e5-93ed-fa0c40a74c6c.png)

**Comment by AlexandreDecan** [comment]
Cela me semble bien. Je propose d'être plus explicite sur le message : "Connexion perdue, le minichat sera rafraîchi automatiquement toutes les 30 secondes."

Je ne sais pas si le bouton "Reconnexion" est nécessaire : si on change de page, normalement le WS va à nouveau s'établir ?

**Comment by roidelapluie** [comment]
![dis](https://cloud.githubusercontent.com/assets/291750/12052993/da00839c-af14-11e5-9b3d-999aef9e22cc.png)

**Comment by roidelapluie** [comment]
Voila

**Comment by AlexandreDecan** [comment]
Yep, en size "small" ce sera encore mieux ;-) Je pense que ce n'est pas nécessaire de mettre une icône "warning" vu qu'on est déjà dans un alert-warning (et que, finalement, ce n'est pas "grave" si la connexion est perdue). Tu en penses quoi ?

**Comment by roidelapluie** [comment]
Super:

![dis](https://cloud.githubusercontent.com/assets/291750/12053321/1c631eb8-af18-11e5-85f5-44f17a78fd4d.png)

**Comment by AlexandreDecan** [comment]
:+1:

**Comment by AlexandreDecan** [comment]
Peut-on fermer ce ticket ?

**Comment by roidelapluie** [comment]
oui; sinon il sera fermé lors du merge la PR des websockets

**Comment by AlexandreDecan** [comment]
Je vais le fermer manuellement alors, car je ne sais pas encore quand je vais merger le PR des WS. D'abord, il faut que l'on finisse l'API (je dois m'arrêter pour ce matin, je dois bosser sur autre chose sinon je vais prendre du retard ^^)
