### ISSUE TITLE
alternative à l'aide?

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#57]
Lexpage avant la version 4 avec une aide bien fournie.

Pour les websokets, il peut être utile d'avoir de l'aide quelque part. Devrais-je créer une 'flatpage'?

**Comment by AlexandreDecan** [comment]
On peut utiliser les flatpages pour ça. Je m'en sers pour "A propos" mais aussi pour l'aide à la rédaction des billets. Je ne suis pas convaincu que les gens lisent l'aide (c'est pour ça que je l'ai retirée lors du passage 3 -> 4 vu les stats) ni qu'ils ont envie de lire quelque chose qui est plutôt "technique", comme les WS. Que souhaiterais-tu y mettre ?

**Comment by roidelapluie** [comment]
En effet je voulais y mettre un peu de technique, mais si les gens ne le lisent pas on pourra se contenter d'un billet dans le forum ;)

**Comment by AlexandreDecan** [comment]
Je pense que c'est mieux. Dans mes souvenirs, l'aide (en dehors des smiley/panneaux) n'était quasiment jamais consultée (max une ou deux fois par mois, pour environ 3000 visites sur le reste du site).
