### ISSUE TITLE
Disable piwik in development environment

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#58]

**Comment by roidelapluie** [comment]
when we run manage.py runserver piwik should be disabled. A setting would be handy.

**Comment by AlexandreDecan** [comment]
Est-ce vraiment nécessaire ? Je désactive les logs pour tout ce qui ne provient pas d'un IP legit... 
Mais c'est vrai que, dans l'absolu, y a pas de raisons que ça passe en local. Peut-être pourrait-on simplement faire un {% if debug %} avant d'inclure analytics ?

**Comment by roidelapluie** [comment]
les tests selenium aussi comportent ceci, de plus à l'avenir si tu as encore besoin de désactiver piwik cela pourrait être pratique?

**Comment by AlexandreDecan** [comment]
Pour désactiver Piwik, je commente juste le fichier :-D 
C'est pas très élégant, mais ça revient au même que de fixer un settings, à part que je peux overrider le settings en prod. Mouais. Ok ;-)

**Comment by roidelapluie** [comment]
Pas la peine de raser des yacks si ce n'est pas nécéssaire ;-)

**Comment by AlexandreDecan** [comment]
Non, je vais le faire, c'est pas un gros changement qui va me demander des heures, hein :-)
