### ISSUE TITLE
Intégrer bootstrap à l'admin Django

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#59]
https://github.com/django-admin-bootstrap/django-admin-bootstrap
- [ ] Compatibilité Django 1.9
- [ ] Compatibilité Mobile
- [ ] Vérifier les collisions potentielles de statics
- [ ] Ne pas dupliquer les statics de BS

**Comment by roidelapluie** [comment]
à tester:

compatibilité django 1.9
compatibilité mobile

**Comment by AlexandreDecan** [comment]
J'avais déjà utilisé Grappeli sur un autre projet, il faudrait que je regarde si ça supporte les appareils mobiles maintenant.... 
https://github.com/sehmaschine/django-grappelli

Pas l'impression....

**Comment by roidelapluie** [comment]
"  Ne pas dupliquer les statics de BS " cela implique que les version de BS se matchent ? si c'est pour faire de l'économie aux clients, cela n'impliquera que les admins donc ce n'est pas si grave?

**Comment by roidelapluie** [comment]
( BS ça me fait penser à bullshit :D )

**Comment by AlexandreDecan** [comment]
Si c'est du BS 3, normalement y aura pas trop de souci. Mais je pense que c'est un peu overkill de vouloir faire ça car il va falloir modifier du code, sans grand intérêt.

**Comment by AlexandreDecan** [comment]
Vu le faible usage que j'ai de l'admin, je ne vais finalement pas ajouter une dépendance supplémentaire "juste" au cas où je l'utilise sur appareil mobile...
