### ISSUE TITLE
API REST pour Lexpage

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#60]
Dans le cadre de #48, il pourrait être intéressant d'avoir une API REST pour certains services du Lexpage, préalable à toute implémentation solide _avec fallback_ de websockets _à la sauce socket.io_. 

En particulier : 
- [x] Contenu du minichat
- [x] Post d'un message sur le minichat
- [x] Liste des utilisateurs (autocomplete) 
- [x] Liste des étiquettes (autocomplete)
- [x] Prévisualisation des markups
- [x] Contenu du message (board)

Une fois cela effectué, les features suivantes seront requises au moins pour #48 : 
- [x] Liste des notifications (toutes et non-lues)
- [x] Dismiss d'une notification

**Comment by roidelapluie** [comment]
Du coup on intégrerait bien angular2 pour travailler avec ces webservices et faire le templating?

**Comment by AlexandreDecan** [comment]
Euh...  NON ! :-D Sérieusement, AngularJS est sympathique, mais c'est bien trop "lourd" pour les features annexes que ça va servir, et la version 2 va casser plein de choses dans l'API qui vont rendre la maintenance difficile. Je suis d'avis, dans un premier temps et vu la simplicité des éléments concernés, de faire le traitement via JQuery 

[Edit : j'avais pas vu que tu parlais d'Angular2. C'est sorti, final et stable ?]

**Comment by roidelapluie** [comment]
Non ce n'est pas sorti stable et final mais tout ce travail va encore prendre du temps. Faire cela en JQuery cela va être une horreur.

**Comment by roidelapluie** [comment]
Ou alors on peut partir vers http://handlebarsjs.com/ ?

**Comment by AlexandreDecan** [comment]
Je ne pense pas qu'un tel framework soit nécessaire, au moins initialement. Avec JQuery, on peut s'en sortir facilement : il faut remplacer le contenu d'un div et on peut générer le nouveau contenu directement via JS, sur base du json récupéré via GET. 

Par contre, le JSON devrait idéalement contenir un marqueur "self" indiquant si on est l'auteur du message ou non (ou alors, il faut exposer le username courant dans la réponse, ou dans la page, par exemple dans ___base.html_ comme on fait avec les URL des WS, si tu te souviens ?). Ce serait plus élégant d'ailleurs que de mettre un booléen "self" dans le json ;-)

**Comment by AlexandreDecan** [comment]
Mercredi ou jeudi, j'aurai un peu de temps pour merger le PR. J'en profiterai pour essayer d'avancer sur les items manquants du premier post, en particulier la prévisualisation des markups (via post au lieu de get, pour ne pas avoir des erreurs à cause d'un entête trop gros). 

Par contre, est-ce que tu as une idée @roidelapluie  comment utiliser django-rest-framework pour l'autocomplete ?
Je dois regarder dans la doc, mais je pense qu'on va grosso-modo s'embêter à refaire ce qu'on a déjà fait au niveau de Django, à part qu'on utiliserait le sérializer que tu as défini pour les _profiles_ au lieu de construire le JSON à la main....

**Comment by roidelapluie** [comment]
Quels markups? je je comprend pas là

**Comment by AlexandreDecan** [comment]
Le markup : BBCode et Markdown, quand tu cliques sur le petit oeil sur la barre d'édition d'un message ou d'un billet ;-)

**Comment by roidelapluie** [comment]
ok

**Comment by roidelapluie** [comment]
Pour les users: http://www.django-rest-framework.org/api-guide/filtering/

**Comment by roidelapluie** [comment]
Liste des utilisateurs (autocomplete) : Done

**Comment by roidelapluie** [comment]
Prévisualisation des markups: #65

**Comment by roidelapluie** [comment]
Liste des étiquettes (autocomplete): Done

**Comment by roidelapluie** [comment]
J'arrête pour aujourd'hui, bon review :sunglasses:

**Comment by AlexandreDecan** [comment]
Je vais merger et voir ce que je peux faire aujourd'hui, j'ai un petit peu de temps devant moi ;)
J'ai ajouté un item dans la liste : la récupération du contenu d'un message sur le forum (on s'en sert quand on fait un "reply"), je pense qu'on peut le convertir vers DRF également.

**Comment by roidelapluie** [comment]
Prévisualisation des markups -> utilise POST mais pas DRF

**Comment by AlexandreDecan** [comment]
En effet, c'est une TemplateView qui retourne l'HTML à injecter. 
Je ne sais pas si c'est pertinent de placer cet HTML dans du json ?

**Comment by roidelapluie** [comment]
Ah oui en effet. Cela semble inutile de passer par DRF.

**Comment by roidelapluie** [comment]
Post d'un message sur le minichat : voir #69

**Comment by AlexandreDecan** [comment]
Tu peux confirmer que pour les notifications, c'est bon (#76) ?

**Comment by roidelapluie** [comment]
Oui, je planche sur les tests seleniums. J'ai besoin de minifier patr contre. Tu utilises quoi?

**Comment by roidelapluie** [comment]
par*

**Comment by AlexandreDecan** [comment]
YUI je pense, via node. Faut que je vérifie sur le laptop, mais je l'ai pas à portée de main là :(

**Comment by roidelapluie** [comment]
Je propose qu'on ferme ce ticket une fois que #83 est mergé. Après cela je propose que tu mettes en prod. Puis je referai ma PR sur les websockets.

**Comment by AlexandreDecan** [comment]
Je merge, je teste, et si j'ai le temps, je passe ça en prod dans la foulée.

**Comment by AlexandreDecan** [comment]
C'est mergé. Ce n'est pas encore en prod, parce que je dois encore faire des tests et que je ne suis pas dispo aujourd'hui (je préfère éviter de pousser en prod sans être là en cas de souci dans les heures qui suivent).

J'ai fait quelques changements supplémentaires, notamment le lien pour "voir" une notification qui n'était pas affiché (tu checkais `notification.action` au lieu de `notifications.show_url`). Normalement, ça devrait être bon. Je dois encore faire d'autres tests.

**Comment by AlexandreDecan** [comment]
Je vais changer les fields exposés, en distinguant `show_url`, `show_and_dismiss_url` et `dismiss_url`.
