### ISSUE TITLE
Empecher certains username

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#61]
Si un utilisateur s'enregistre avec le username edit ou list, le lien vers son profil sera cassé car cela est en conflit avec l'adresse web pour éditer ou lister les profils.

**Comment by AlexandreDecan** [comment]
Bien vu !

**Comment by roidelapluie** [comment]
On peut aussi essayer d'utiliser d'autres URLs.

**Comment by AlexandreDecan** [comment]
Pour l'édition, <username>/edit irait. Mais pour la liste, c'est plus délicat.

**Comment by AlexandreDecan** [comment]
Il faut que je vérifie si ce PR n'a pas un impact caché sur certaines URL "en dur" (à priori, non, car j'utilise le reverse de Django pratiquement partout).
