### ISSUE TITLE
Prévisualisation du markup en POST plutôt qu'en GET

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#65]
En parallèle du #60, ou à la place, il faudrait que l'appel pour la prévisualisation soit géré via POST plutôt que GET, pour éviter une taille d'entête trop importante.
- [x] changer le JS https://github.com/AlexandreDecan/Lexpage/blob/master/app/commons/static/js/markup.js#L163
- [x] adapter la vue https://github.com/AlexandreDecan/Lexpage/blob/master/app/commons/views_markup.py
- [x] supprimer la config gunicorn https://github.com/AlexandreDecan/Lexpage/blob/master/gunicorn.py#L14

**Comment by roidelapluie** [comment]
Pourquoi?

**Comment by AlexandreDecan** [comment]
Pourquoi quoi ? :-D
Essentiellement parce que pour permettre d'utiliser la prévisualisation sur des longs messages, il a fallu augmenter la taille de l'entête autorisée par gunicorn (ou uwsgi, à l'époque). J'aimerai lever cette limitation, et le passage en POST n'est pas couteux pour moi (je ne sais plus pour quelles raisons je ne l'avais pas fait à l'époque, d'ailleurs !).

**Comment by roidelapluie** [comment]
Je ne comprenais pas la signification de markup :)

**Comment by roidelapluie** [comment]
à réouvrir

**Comment by AlexandreDecan** [comment]
Pourquoi ?

**Comment by roidelapluie** [comment]
Je n'avais pas vu le commit :)

**Comment by AlexandreDecan** [comment]
Ok :-)
