### ISSUE TITLE
Intégration de Grunt pour les tâches usuelles

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#67]
Tâches Grunt : 
- [ ] Compilation des templates nunjucks minichat
- [ ] Compilation des templates nunjucks notification
- [ ] Compilation du style sass du Lexpage
- [ ] Compilation du style sass de Nowell
- [ ] Déplacement des fichiers statiques (via django collectstatic ?)
- [ ] Minification des css dans static_pub
- [ ] Minification des js dans static_pub

De même, il serait intéressant de pouvoir mettre à jour aisément certaines librairies requises : 
- [ ] Bootstrap (_static/libs/bootstrap_ mais aussi _static/css/bootstrap_ --> embêtant !)
- [ ] JQuery (_static/libs/jquery_) et modules (_static/libs_)
- [ ] font-awesome (_static/libs/font-awesome_)
- [ ] nunjucks (_static/libs/nunjucks_)
- [ ] modernizr.js (_static/libs_)
- [ ] moments.js

Corollaire : 
- [ ] Mettre le README à jour
- [ ] Lister les dépendances nécessaires (gem sass, nunjucks, grunt, minify, ...)

**Comment by roidelapluie** [comment]
à intégrer avec manage.py  si possible?

**Comment by AlexandreDecan** [comment]
Non, je ne pense pas que ça soit utile. Les deux sont relativement indépendants (et quand j'avais testé django-pipeline, je n'avais pas été convaincu). Par ailleurs, cette issue concerne surtout la partie "development" et non pas la prod, donc pas utile d'automatiser (trop) directement dans Django. 

Il va falloir que je me retape la doc de npm, bower et grunt, parce que ça fait près d'un an que je n'ai plus vraiment utilisé ces outils :-D

**Comment by AlexandreDecan** [comment]
Updated

**Comment by roidelapluie** [comment]
moment.js // attention on utilise notre propre locale

**Comment by AlexandreDecan** [comment]
Quel est exactement le souci ? Parce que les locales personnalisées peuvent être configurées sans avoir à toucher à la librairie en tant que tel ? 
http://momentjs.com/docs/#/customization/

**Comment by roidelapluie** [comment]
la compatibilité exacte avec le filtre |naturalday de django, que l'on vérifie dans nos tests

**Comment by AlexandreDecan** [comment]
On peut déplacer le support de nos locales en dehors de la lib, de sorte à ce qu'une mise à jour de Moment.js ne vienne pas écraser nos préférences.

**Comment by AlexandreDecan** [comment]
Il est temps de supprimer les *.min.[js|css] des sources, le projet est étiquetté comme "Javascript" et non plus "Python" :-D

Je vais regarder s'il n'est pas possible d'automatiser quelque chose coté serveur, et donc de n'avoir que les sources non-minifiées dans le dépôt, et je minifie à la volée lorsque les pages sont servies (ou encore une tâche grunt qui minifie _in place_ dans static_pub sur le serveur).

**Comment by AlexandreDecan** [comment]
Je me demande si on ne peut pas, dans un premier temps, se simplifier la vie et laisser de coté la minification des js et css, même en prod. Nginx est configuré pour gzipper les ressources qu'il sert, le gain est déjà très important (environ 50 à 75%). De ce que je vois sur le net, le gain de combiner min+gz par rapport à simplement gz est de l'ordre de 20%. Avec la mise en cache des ressources, c'est sans doute négligeable. 

J'aimerai ton avis sur la question, @roidelapluie ?

**Comment by roidelapluie** [comment]
Je suis pour, c'est surement négligeable, à tester.  Sinon: http://www.newmediacampaigns.com/blog/Automatic-file-minification-on-nginx

**Comment by AlexandreDecan** [comment]
Ok. Quoiqu'il en soit, les étapes suivantes seront nécessaires : 
- [ ] Supprimer les fichiers minifiés "locaux" (comprendre : markup, script, etc. mais pas JQuery, Moment, etc. qui sont des libs externes dont on peut raisonnablement conserver la minification en prod)
- [ ] Adapter les liens dans _**base**.html_ (notamment le filtre `static_ext`). 
- [ ] Vérifier dans les différentes apps qu'aucune template n'ajoute un JS utilisant encore `static_ext` (par exemple, JQuery.autocomplete ou JQuery.tagcloud).

**Comment by AlexandreDecan** [comment]
Tiens, que penses-tu de http://django-compressor.readthedocs.org/en/latest/ ?
On peut le faire tourner avec https://pypi.python.org/pypi/csscompressor/ et https://github.com/rspivak/slimit et rester en 100% Python.

Même en l'absence de django-compressor, il pourrait être intéressant de considérer ces deux outils comme les outils de minifications par "défaut", et d'étendre la commande "collectstatic" afin d'inclure une minification à la volée lors de la collecte des ressources. Qu'en penses-tu ?

**Comment by roidelapluie** [comment]
J'en pense du bien, ça peut nous faciliter la vie.

**Comment by roidelapluie** [comment]
Peut etre que on peut se passer de compressor et faire un collectstatic_and_minify

**Comment by AlexandreDecan** [comment]
Je pense aussi. Django-compressor nécessiterait encore d'alourdir les settings, alors que étendre/surcharger la commande collectstatic parait naturel, vu que c'est une commande qu'on utilise de toute façon dans le workflow. 

Je vais me renseigner dans la documentation Django pour voir ce qui est disponible à ce niveau (j'imagine que ça ne va pas être "si simple" que ça ;-))

**Comment by roidelapluie** [comment]
Si.

**Comment by roidelapluie** [comment]
Par contre css compressor ça va pas compiler le CSS et slimit va pas compiler les templates nunjucks.

**Comment by roidelapluie** [comment]
Ce que je veux dire c'est priorité à grunt ? la minification c'est moins important ?

**Comment by AlexandreDecan** [comment]
On a grosso-modo deux approches possibles : 
1. Supprimer les "min.x" internes (pas les libs qu'on a cut&paste) et adapter les templates. Nginx fera la compression dans un premier temps, et on pourra utiliser https://docs.djangoproject.com/en/1.9/howto/custom-file-storage/ pour minifier à la volée lors du _collectstatic_. On définit des tâches Grunt pour SCSS et Nunjucks.
2. On définit des tâches Grunt pour SCSS, Nunjucks et la minification des JS et CSS. La tâche de minification s'appliquera (ou peut s'appliquer) sur _static_pub/_ manuellement après avoir fait le _collectstatic_ (ainsi on peut servir le fichier sans changer son nom).

J'ai une préférence pour (1) pour ne pas (trop) dépendre de JS/Grunt/Node, et pour (2) pour ne pas multiplier les approches inutilement (tout ce qui concerne le static serait géré via Grunt, point).

Ton avis ?

**Comment by roidelapluie** [comment]
En effet, 1 semble adapté et le plus simple

**Comment by AlexandreDecan** [comment]
Issue splittée vers #109, #110 et #111.
