### ISSUE TITLE
Renommer le projet

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#68]
Le nom du projet devrait être changé, de même que le nom de Lexpage dans les templates. On devrait introduire un SETTINGS pour changer le nom du site.

Ce n'est pas une demande fantaisiste, c'est pour:
1. découpler le logiciel du site
2. permettre à d'autres personnes d'installer leur version du Lexpage
3. éviter que les autres instances du lexpage n'utilisent le nom Lexpage, en particulier cela serait embetant sur les moteurs de recherche

**Comment by AlexandreDecan** [comment]
Oulha, si ça ne venait pas de toi, je ne prendrai pas cette issue au sérieux ;-) 
Je ne suis cependant pas totalement convaincu que ça soit pertinent : 
1. Ok pour le découplage, mais en général, ce sont les apps qui sont réutilisables, et non pas le projet dans son ensemble (du moins, dans la philosophie Django).
   2 & 3. Des personnes peuvent déjà l'installer localement. Souhaite-t-on vraiment qu'il soit possible de créer un clone du Lexpage en n'ayant juste à changer un nom dans les settings ? 

Peux-tu détailler en particulier les points 2 et 3 de ton message initial, parce que je ne suis pas sûr d'identifier toutes les "implications" d'un changement de nom (je ne parle pas d'implications sur ce dépôt, mais dans l'absolu pour le "projet" et les usages).

**Comment by roidelapluie** [comment]
"Souhaite-t-on vraiment qu'il soit possible de créer un clone du Lexpage en n'ayant juste à changer un nom dans les settings ? "

ça c'est pour le point 2. Le problème n'est pas "souhaite-t-on" mais plutot "si quelqu'un". Dans le cadre actuel n'importe qui peut déployer un lexpage et l'appeler lexpage, vu que le nom est hardcodé. je crois qu'avoir un nom 'neutre' a la place permettrait d'éviter les problèmes.

Le point 3: si je veux déployer une version de test de Lexpage actuellement, elle sera référencée par google comme lexpage également à moins que je ne patche tout partout, et donc cela a plus de sens d'intégrer la possibilité de changer le nom en upstream.

D'un point de vue pratique pour le dépot, pas grand chose ne changerait. Tu aurais juste SITE_TITLE="Lexpage" dans settings_prod.

Pour le projet, pas grande différence non plus, il faudra juste renommer le dépot github.

**Comment by AlexandreDecan** [comment]
Ok pour le setting, ça ne demande pas beaucoup d'effort de toute façon ;-)
Par contre, pour le dépôt GitHub, est-ce que cela a du sens ? 

Je veux dire : quand je prends une lib sur GitHub, comme DRF (en fait, je sais même pas si c'est sur GitHub), ils ne fournissent ni mécanisme pour changer le nom de la lib, et ils n'ont pas un dépôt spécial "abstract-django-rest-framework" qu'ils instancient en DRF sur Pypi par exemple. Non ?

**Comment by roidelapluie** [comment]
Ce sont des libraries, pas des sites, mais OK, un settings ce sera un bon début :)

Pour donner des contres exemples:
- Wikipedia est appelé médiawiki
- Sourceforge est apellé Allura
- identi.ca c'est pump.io

et il y a plein d'autres exemples.

**Comment by AlexandreDecan** [comment]
Gna gna gna ok :-)

**Comment by AlexandreDecan** [comment]
Ref #92

**Comment by AlexandreDecan** [comment]
On peut fermer ?
Je ne sais pas si cela s'avère intéressant pour l'instant de continuer dans cette direction (je suppose que l'idée serait de dissocier les deux dépôts ?).

**Comment by AlexandreDecan** [comment]
Ou d'avoir une branche "projet principal" et l'autre avec le fork pour lexpage ?

**Comment by roidelapluie** [comment]
Ah bon? pourquoi tu merges pas tout simplement?

**Comment by AlexandreDecan** [comment]
C'était déjà fait au moment du message :-)
