### ISSUE TITLE
utiliser https pour analytics.lexpage.net

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#79]
Cela peut être mis en place maintenant, cela te permettra de connaitre let's encrypt et de te faire la main.

**Comment by AlexandreDecan** [comment]
Est-ce que ça marche d'envoyer des data vers https depuis un site en http ?
[Edit : je sais que ça marche, mais je veux dire : est-ce legit? ]

**Comment by roidelapluie** [comment]
Oui; pourquoi pas?

**Comment by roidelapluie** [comment]
Je ne crois pas que Google analytics serve encore en plain http

**Comment by AlexandreDecan** [comment]
Je reconsidèrerai cela plus tard, quand j'envisagerai de passer l'ensemble des webapps du serveur en HTTPS.
