### ISSUE TITLE
Implement SIMPLIFIED selenium tests

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#81]
I will extract and simplify A LOT the selenium tests of the websockets and use that to test the recent pull requests (the API and client-side templates rendering in JS).

**Comment by roidelapluie** [comment]
To do the simplification, I will only use firefox and chrome that are built-in in travis, so we will remove a lot of complexity.

**Comment by AlexandreDecan** [comment]
:+1:
