### ISSUE TITLE
Homepage: backgrounds are not contained in their blog items

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#84]
![homepage](https://cloud.githubusercontent.com/assets/291750/12217120/beda28c2-b6f6-11e5-8cf0-ec8655cbdd17.png)

**Comment by AlexandreDecan** [comment]
J'avais déjà remarqué ça, mais je n'ai aucune idée pour l'éviter. C'était un bricolage (sympathique, mais bricolage tout de même) lors de l'introduction de la skin...

**Comment by AlexandreDecan** [comment]
Tchou: 

> Ça me semble compliqué car tu sors un item du flow avec un absolute en voulant que le flow s'impose à lui après. Actuellement c'est un effet réussi, mais compliqué car fait à base de font et de positionnement absolu, on a deux blocs de texte chevauchés. Le plus simple serai de mettre l'image en background, mais j'avoue ne pas savoir s'il est possible de faire un background composé de texte. C'est possible avec du svg, si la typo employée a une version svg.
> 
> Une solution "quick and dirty" serai de caler une taille précise au bloc décoratif (actuellement, on a une taille typo de 10em (qui s'adapte donc) et des pixels, donc on additionne des oranges et des tomates), et de prévoir le bloc contenant la news avec un min-height correspondant. Un verical-align: super sur le typo aiderai pour caler ça précisément, là ça a été fait un peu à l'aveugle je dirai (ce qui n'empêche que c'est réussi, je répète : un brin bidouille dans l'implémentation, mais très réussi).

**Comment by AlexandreDecan** [comment]
A vérifier : 

> Pour aligner le texte sur le haut du bloc, par défaut le texte est aligné sur le milieu de sa ligne.
> 
> Rajoute un background: pink (j'adore le pink pour tester, ce pink-là est tellement moche qu'il est impossible de l'oublier) à .post-icon-bg pour comprendre le soucis.
> 
> Maintenant, rajoute vertical-align: super au span qui suit : oh merveille, je n'ai plus à calculer au pif, je cale donc le haut de mon icone pile où je veux qu'elle soit au lieu de calculer au doigt mouillé ... et quand il faut calculer la moitié de 10em + 6px, ça devient plus périlleux, car l'em dépend de chaque browser/OS/préférences.
