### ISSUE TITLE
Twicy

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#90]
A l'instar d'un jeu de pronostics, Twicy vous propose de miser des sommes virtuelles, des franpignonz (FPz) sur des évènements de l'actualité, qu'ils soient sportifs, politiques, people, ... ou insolites !

Toute personne déjà inscrite sur Lexpage peut débuter Twicy directement. Si vous n'êtes pas encore inscrit, c'est l'occasion de le faire, c'est très rapide.
Une fois inscrit, rendez-vous sur la page d'évènements. Cette page reprend l'ensemble des paris actuellement en cours. Parmi ceux-ci, certains paris sont « cloturés » : on ne peut plus miser dessus.

Choisissez un pari ou plusieurs paris dans cette liste. N'espérez pas gagner à Twicy si vous misez toute votre richesse dans un seul et unique pari ! Diversifiez-vous et profitez de votre somme de départ pour aborder un maximum de paris ! De toute façon, vous ne pouvez pas miser plus de 50% de votre richesse. Veillez également à ne pas miser uniquement sur des paris dont la cloture est encore lointaine : votre argent dormirait bêtement sur ce pari pendant plusieurs jours, et ne vous rapporterait rien.

Une fois le ou les pari(s) choisi(s), il ne vous reste plus qu'à le lire attentivement, sélectionner votre pronostic, fixer votre mise et c'est parti ! D'ici quelques jours, le pari passera en « cloturé » puis en « en attente des résultats ». Dès que les résultats seront validés, vous serez prévenu par Lexmail (la messagerie interne) de votre résultat. Vous pouvez à tout moment suivre l'évolution du jeu via le journal : nouveaux paris, paris validés, nouveaux joueurs, mises, ... N'hésitez pas à participer sur le forum où, en plus des discussions généralement totalement déjantées, certains sujets parlent également de Twicy.

Que peut-on gagner en jouant à Twicy ? Pas de célébrités, ni de cadeaux capitalistes. Uniquement une maigre gloire auprès des autres joueurs. Cette gloire, vous la constaterez dans le classement. Vous débuterez en division 4 de ce classement. Pour monter, rien de plus simple : être parmi les 20% meilleurs de votre division. Mais attention, le tarif est le même pour descendre, et quitter la division 5 par le bas est synonyme de fin de partie ! Si vous n'êtes pas trop mauvais, cela ne devrait pas arriver. Et, dans le pire des cas, vous recevrez de toute façon une petite somme chaque semaine pour vous permettre de vous refaire.
- [ ] Définir une esquisse d'UI en se basant sur la V3
- [ ] Permettre de ratacher des messages de forum à d'autres modèles de manière générique (pas que à des blog posts)
- [ ] définir les modèles nécéssaires et leur champs
- [ ] retrouver/définir les règles et les traduire en tests

Features:
- [ ] Support des "saisons"
- [ ] Support des FPz (transactionnel ou fixes? surement les deux)
- [ ] Permettre de définir les saisons twicy dans l'admin et cacher twicy si on n'est pas dans une session
- [ ] Support de permissions spéciales pour permettre aux utilisateurs sélectionnés de valider ou pas des paris
- [ ]  se renseigner sur les API externes que l'on peut utiliser pour valider les paris
- [ ] permettre d'annuler un paris ou de changer le résultat après validation
- [ ] Garder un historique des notifications twicy ? Ou utiliser les lexmails?
- [ ] Permettre la proposition de paris
- [ ] permettre aux applications d'ajouter des fields dans le profil et le forum  (FPz par exemple)

**Comment by AlexandreDecan** [comment]
Euh ouais, ok, mais le gros souci de Twicy, c'est pas de le coder (bien que c'est déjà un gros morceau si on veut une feature parity avec Lexpage v3), mais plutôt de le "maintenir" (paris, résultats, etc.).

**Comment by roidelapluie** [comment]
Je lance la discussion sur le forum. As tu des règles plus précises sous la main que celles que j'ai retrouvées?

**Comment by AlexandreDecan** [comment]
Non, mais les règles sont tout à fait classiques (y compris le calcul des cotes). 

La seule "subtilité" venait sans doute des mises min/max autorisées, ainsi que du calcul de certains indicateurs dans les classements (mais qui étaient purement virtuels). Je dois pouvoir retrouver ça, si nécessaire, dans le code de la v3. 

Mais je maintiens : ce qui me retient le plus avec Twicy, c'est la quantité de travail que cela représente pour organiser une saison. L'ajout, la vérification et la validation des paris est quelque chose de chronophage. Quand les enfants n'étaient pas encore nés, ça m'était déjà difficile de concilier cela avec le travail par moment, alors je n'ose pas imaginer ce que ça doit être maintenant ;-)

**Comment by AlexandreDecan** [comment]
Je ferme, on ouvrira si un jour on repart sur l'idée, mais je préfère qu'on se focalise sur ALDP.
