### ISSUE TITLE
Désactiver la validation des mots de passe en DEBUG

### ISSUE THREAD

**Issue by AlexandreDecan** [AlexandreDecan/Lexpage#93]
Comme souligné dans cet article sur Sam&Max, cela vaudrait la peine de désactiver la validation des mots de passe en DEBUG:

http://sametmax.com/desactiver-la-validation-des-mots-de-passe-en-mode-debug-sous-django/

**Comment by roidelapluie** [comment]
Au lieu de l'approche if DEBUG je préfère mettre la validation dans _common et l'enlever dans _dev

**Comment by AlexandreDecan** [comment]
Je suis d'accord avec toi. 

Je pense aussi (mais ça devrait peut-être faire l'objet d'une issue distincte) qu'on devrait doucement commencer à documenter les nombreux settings non-standards qu'on injecte dans le projet ;-)

**Comment by roidelapluie** [comment]
Et si au lieu de ça on activait ça que en prod?

**Comment by AlexandreDecan** [comment]
Les settings de prod ne sont pas versionnés, donc je préfère mettre le maximum dans settings_common :-D De plus, settings_common est supposé représenter l'environnement "par défaut" qu'on utilise (modulo les changements fait spécifiquement pour l'un ou l'autre environnement), ce qui me pousse à définir ça dans _common plutôt que dans _prod.

**Comment by AlexandreDecan** [comment]
Je ferme, je ne vois plus les validateurs dans le code, et je suis également convaincu que ce n'est pas la bonne approche que de masquer un risque de password faible juste avec quelques validateurs basiques.

**Comment by roidelapluie** [comment]
Tu les as virés en mergeant le passage à 1.9 sans passer vriament à 1.9 iirc

**Comment by AlexandreDecan** [comment]
Probablement, ce n'est pas plus mal ;-)
