### ISSUE TITLE
Incohérence entre la taille du titre des billets et celle du forum

### ISSUE THREAD

**Issue by roidelapluie** [AlexandreDecan/Lexpage#98]
![size](https://cloud.githubusercontent.com/assets/291750/12364831/4cd425c2-bbd1-11e5-89a1-fe08b0d18891.png)
Si on crée un thread à propos d'un blogpost qui a un titre de 100 caractères ça ne passe pas du premier coup.

Que faire?

Tronquer automatiquement?
Augmenter la limite pour le forum?
Diminuer la limite pour le blog ?

**Comment by roidelapluie** [comment]
Devrait-on d'ailleur permettre aux utilisateurs de modifier ce titre?

**Comment by AlexandreDecan** [comment]
On peut sans doute modifier la valeur initiale du formulaire de sorte à tronquer à la longueur souhaitée. Y a un filtre, wordwrap, dans les templates pour ça, qui tient compte des "mots". On peut en faire usage dans forms.py si on ne veut pas se compliquer la vie.

**Comment by AlexandreDecan** [comment]
Le titre est automatiquement tronqué (au mot près) si la taille dépasse celle définie dans le champ.
